// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("accountonlinetime")]
public partial class Accountonlinetime
{
    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("loggedin", TypeName = "datetime")]
    public DateTime Loggedin { get; set; }

    [Column("loggedout", TypeName = "datetime")]
    public DateTime? Loggedout { get; set; }

    [Required]
    [Column("ip")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ip { get; set; }

    [Column("safelogout")]
    public bool Safelogout { get; set; }

    [Column("hwhash")]
    [StringLength(50)]
    [Unicode(false)]
    public string Hwhash { get; set; }

    [Column("istrial")]
    public bool Istrial { get; set; }
}