// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("accountredeemableitems")]
public partial class Accountredeemableitem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("redeemed", TypeName = "datetime")]
    public DateTime? Redeemed { get; set; }

    [Column("characterid")]
    public int? Characterid { get; set; }

    [Column("wasredeemed")]
    public bool Wasredeemed { get; set; }

    [Column("packageid")]
    public int? Packageid { get; set; }
}