// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("accounttransactionlog")]
public partial class Accounttransactionlog
{
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("accountId")]
    [StringLength(10)]
    public string AccountId { get; set; }

    [Column("transactionType")]
    public int TransactionType { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("eid")]
    public long? Eid { get; set; }

    [Column("credit")]
    public int Credit { get; set; }

    [Column("creditChange")]
    public int CreditChange { get; set; }

    [Column("created", TypeName = "datetime")]
    public DateTime Created { get; set; }
}