// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("adminCommandLog")]
public partial class AdminCommandLog
{
    [Column("id")]
    public int Id { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("accLevel")]
    public int AccLevel { get; set; }

    [Column("message")]
    [StringLength(255)]
    public string Message { get; set; }
}