// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("aggregatevalues")]
[Index("Definition", "Field", Name = "IX_aggregatevalues", IsUnique = true)]
public partial class Aggregatevalue
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("field")]
    public int Field { get; set; }

    [Column("value")]
    public double Value { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Aggregatevalues")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Field")]
    [InverseProperty("Aggregatevalues")]
    public virtual Aggregatefield FieldNavigation { get; set; }
}