// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("aggregatefields")]
[Index("Name", Name = "IX_aggregatefields", IsUnique = true)]
public partial class Aggregatefield
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("formula")]
    public int Formula { get; set; }

    [Column("measurementunit")]
    [StringLength(100)]
    [Unicode(false)]
    public string Measurementunit { get; set; }

    [Column("measurementmultiplier")]
    public double Measurementmultiplier { get; set; }

    [Column("measurementoffset")]
    public double Measurementoffset { get; set; }

    [Column("category")]
    public int Category { get; set; }

    [Column("digits")]
    public int Digits { get; set; }

    [Column("moreisbetter")]
    public bool? Moreisbetter { get; set; }

    [Column("usedinconfig")]
    public bool? Usedinconfig { get; set; }

    [Column("note")]
    public string Note { get; set; }

    [InverseProperty("FieldNavigation")]
    public virtual ICollection<Aggregatevalue> Aggregatevalues { get; set; } = new List<Aggregatevalue>();

    [InverseProperty("Targetproperty")]
    public virtual ICollection<Chassisbonu> Chassisbonus { get; set; } = new List<Chassisbonu>();

    [InverseProperty("FieldNavigation")]
    public virtual ICollection<Effectdefaultmodifier> Effectdefaultmodifiers { get; set; } = new List<Effectdefaultmodifier>();

    [InverseProperty("Targetproperty")]
    public virtual ICollection<Extension> Extensions { get; set; } = new List<Extension>();

    [InverseProperty("FieldNavigation")]
    public virtual ICollection<Nstemplate> Nstemplates { get; set; } = new List<Nstemplate>();
}