// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("alliances")]
[Index("Name", Name = "IX_alliances_name", IsUnique = true)]
[Index("Nick", Name = "IX_alliances_nick", IsUnique = true)]
public partial class Alliance
{
    /// <summary>
    /// link to the entity
    /// </summary>
    [Key]
    [Column("allianceEID")]
    public long AllianceEid { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [Column("nick")]
    [StringLength(6)]
    [Unicode(false)]
    public string Nick { get; set; }

    /// <summary>
    /// dev note for ai alliances (factions)
    /// </summary>
    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("defaultAlliance")]
    public bool DefaultAlliance { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Column("logoresource")]
    [StringLength(50)]
    [Unicode(false)]
    public string Logoresource { get; set; }

    [Column("id")]
    public int Id { get; set; }

    [Column("raceid")]
    public int? Raceid { get; set; }
}