// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("artifactloot")]
public partial class Artifactloot
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("artifacttype")]
    public int Artifacttype { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("minquantity")]
    public int Minquantity { get; set; }

    [Column("maxquantity")]
    public int Maxquantity { get; set; }

    [Column("chance")]
    public double Chance { get; set; }

    [Column("packed")]
    public bool Packed { get; set; }
}