// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("artifactspawninfo")]
public partial class Artifactspawninfo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("artifacttype")]
    public int Artifacttype { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("rate")]
    public double Rate { get; set; }
}