// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("attributeFlags")]
[Index("Offset", Name = "IX_attributeFlags_offset", IsUnique = true)]
public partial class AttributeFlag
{
    [Column("offset")]
    public int Offset { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }
}