// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("beamassignment")]
[Index("Definition", Name = "IX_beamassignment", IsUnique = true)]
public partial class Beamassignment
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("beam")]
    public int Beam { get; set; }

    [ForeignKey("Beam")]
    [InverseProperty("Beamassignments")]
    public virtual Beam BeamNavigation { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Beamassignment")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}