// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("calibrationtemplateitems")]
public partial class Calibrationtemplateitem
{
    [Column("definition")]
    public int? Definition { get; set; }

    [Column("targetdefinition")]
    public int? Targetdefinition { get; set; }
}