// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("categoryFlags")]
[Index("Value", Name = "IX_categoryFlags", IsUnique = true)]
public partial class CategoryFlag
{
    [Key]
    [Column("value")]
    public long Value { get; set; }

    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [Column("hidden")]
    public bool Hidden { get; set; }

    [Column("isunique")]
    public bool Isunique { get; set; }

    [InverseProperty("CategoryflagNavigation")]
    public virtual Productiondecalibration Productiondecalibration { get; set; }
}