// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("centralbanklog")]
public partial class Centralbanklog
{
    [Column("eventday", TypeName = "datetime")]
    public DateTime Eventday { get; set; }

    [Column("amount")]
    public long Amount { get; set; }
}