// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("centralbanktransactions")]
public partial class Centralbanktransaction
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("transactiontype")]
    public int Transactiontype { get; set; }

    [Column("amount")]
    public double Amount { get; set; }

    [Column("bankcredit")]
    public long Bankcredit { get; set; }
}