// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("channels")]
[Index("Name", Name = "IX_channels_name", IsUnique = true)]
public partial class Channel
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("password")]
    [StringLength(50)]
    public string Password { get; set; }

    [Column("topic")]
    [StringLength(200)]
    public string Topic { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("isForcedJoin")]
    public bool? IsForcedJoin { get; set; }
}