// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("characterhighscore")]
[Index("Characterid", Name = "IX_characterhighscore")]
[Index("Date", Name = "characterhighscore_ixx")]
public partial class Characterhighscore
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("npcskilled")]
    public int Npcskilled { get; set; }

    [Column("playerskilled")]
    public int Playerskilled { get; set; }

    [Column("date", TypeName = "datetime")]
    public DateTime? Date { get; set; }
}