// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("characterreimburselog")]
public partial class Characterreimburselog
{
    [Column("containereid")]
    public long? Containereid { get; set; }

    [Column("characterid")]
    public int? Characterid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }
}