// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("charactermessages")]
public partial class Charactermessage
{
    [Column("mailid")]
    public long Mailid { get; set; }

    [Column("owner")]
    public int Owner { get; set; }

    [Column("sender")]
    public int Sender { get; set; }

    [Column("folder")]
    public int Folder { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Required]
    [Column("targets")]
    [StringLength(512)]
    [Unicode(false)]
    public string Targets { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime? Creation { get; set; }

    [Column("subject")]
    [StringLength(128)]
    public string Subject { get; set; }

    [Column("body")]
    [StringLength(2000)]
    public string Body { get; set; }

    [Column("wasread")]
    public bool Wasread { get; set; }
}