// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("characterextensions")]
public partial class Characterextension
{
    [Key]
    [Column("characterextensionid")]
    public int Characterextensionid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("extensionlevel")]
    public int? Extensionlevel { get; set; }

    [ForeignKey("Extensionid")]
    [InverseProperty("Characterextensions")]
    public virtual Extension Extension { get; set; }
}