// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("characternpcdeath")]
public partial class Characternpcdeath
{
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("npcdefinition")]
    public int Npcdefinition { get; set; }

    [Column("playersrobot")]
    public int Playersrobot { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }
}