// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("characters")]
[Index("AccountId", Name = "IX_characters_account")]
[Index("ActiveChassis", Name = "IX_characters_activechassis")]
[Index("RootEid", Name = "IX_characters_rooteid")]
[Index("Nick", Name = "IX_nickUnique", IsUnique = true)]
[Index("BaseEid", "Active", "Docked", Name = "pbshelp")]
public partial class Character
{
    [Key]
    [Column("characterID")]
    public int CharacterId { get; set; }

    [Column("accountID")]
    public int? AccountId { get; set; }

    [Column("rootEID")]
    public long RootEid { get; set; }

    [Column("nick")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nick { get; set; }

    [Column("moodMessage")]
    [StringLength(2000)]
    public string MoodMessage { get; set; }

    [Column("creation", TypeName = "smalldatetime")]
    public DateTime? Creation { get; set; }

    [Column("lastLogOut", TypeName = "smalldatetime")]
    public DateTime? LastLogOut { get; set; }

    [Column("lastUsed", TypeName = "smalldatetime")]
    public DateTime? LastUsed { get; set; }

    [Column("credit")]
    public double Credit { get; set; }

    [Column("inUse")]
    public bool InUse { get; set; }

    [Column("totalMinsOnline")]
    public int TotalMinsOnline { get; set; }

    [Column("activeChassis")]
    public long? ActiveChassis { get; set; }

    /// <summary>
    /// false if the character is deleted
    /// </summary>
    [Column("active")]
    public bool Active { get; set; }

    /// <summary>
    /// the time when the character was deleted
    /// </summary>
    [Column("deletedAt", TypeName = "smalldatetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("baseEID")]
    public long? BaseEid { get; set; }

    [Column("defaultcorporationEID")]
    public long? DefaultcorporationEid { get; set; }

    [Column("majorID")]
    public int MajorId { get; set; }

    [Column("raceID")]
    public int RaceId { get; set; }

    [Column("schoolID")]
    public int SchoolId { get; set; }

    [Column("sparkID")]
    public int SparkId { get; set; }

    [Column("lastdocked", TypeName = "datetime")]
    public DateTime? Lastdocked { get; set; }

    [Column("docked")]
    public bool Docked { get; set; }

    [Column("lastteleported", TypeName = "datetime")]
    public DateTime? Lastteleported { get; set; }

    [Column("zoneID")]
    public int? ZoneId { get; set; }

    [Column("nickcorrected")]
    public bool Nickcorrected { get; set; }

    [Column("offensivenick")]
    public bool Offensivenick { get; set; }

    [Column("positionX")]
    public double? PositionX { get; set; }

    [Column("positionY")]
    public double? PositionY { get; set; }

    [Column("homeBaseEID")]
    public long? HomeBaseEid { get; set; }

    [Column("blockTrades")]
    public bool BlockTrades { get; set; }

    [Column("globalMute")]
    public bool GlobalMute { get; set; }

    [Column("avatar")]
    [Unicode(false)]
    public string Avatar { get; set; }

    [Column("note")]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("corporationeid")]
    public long Corporationeid { get; set; }

    [Column("allianceeid")]
    public long? Allianceeid { get; set; }

    [Column("language")]
    public int Language { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastRespec { get; set; }
}