// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("charactersocial")]
public partial class Charactersocial
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("friendid")]
    public int Friendid { get; set; }

    [Column("socialstate")]
    public byte Socialstate { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("laststateupdate", TypeName = "datetime")]
    public DateTime Laststateupdate { get; set; }
}