// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("charactersettings")]
public partial class Charactersetting
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("settingsstring")]
    public string Settingsstring { get; set; }
}