// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("charactersparkteleports")]
[Index("Characterid", "Baseeid", Name = "IX_charactersparkteleports", IsUnique = true)]
public partial class Charactersparkteleport
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("baseeid")]
    public long Baseeid { get; set; }

    [Column("basedefinition")]
    public int Basedefinition { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }
}