// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("charactertransactions")]
[Index("Containereid", Name = "IX_CharacterTransactions_ContainerEid")]
public partial class Charactertransaction
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("transactiontype")]
    public int Transactiontype { get; set; }

    [Column("amount")]
    public double Amount { get; set; }

    [Column("transactiondate", TypeName = "datetime")]
    public DateTime Transactiondate { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("currentcredit")]
    public double Currentcredit { get; set; }

    [Column("othercharacter")]
    public int? Othercharacter { get; set; }

    [Column("containereid")]
    public long? Containereid { get; set; }
}