// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("characterkillreports")]
[Index("Characterid", "Victim", Name = "characterkillreports_ixx")]
public partial class Characterkillreport
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("reportid")]
    public Guid Reportid { get; set; }

    [Column("victim")]
    public bool? Victim { get; set; }

    [Column("attacker")]
    public bool? Attacker { get; set; }

    [Column("killer")]
    public bool? Killer { get; set; }
}