// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("charactersparks")]
public partial class Characterspark
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("sparkid")]
    public int Sparkid { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Column("activationtime", TypeName = "datetime")]
    public DateTime? Activationtime { get; set; }
}