// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("characternickhistory")]
public partial class Characternickhistory
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("nick")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nick { get; set; }

    [Column("eventdate", TypeName = "datetime")]
    public DateTime Eventdate { get; set; }
}