// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("chassisbonus")]
[Index("Definition", "Extension", "TargetpropertyId", Name = "IX_chassis_bonus", IsUnique = true)]
public partial class Chassisbonu
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("extension")]
    public int Extension { get; set; }

    [Column("bonus")]
    public double Bonus { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("targetpropertyID")]
    public int TargetpropertyId { get; set; }

    [Column("effectenhancer")]
    public bool Effectenhancer { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Chassisbonus")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Extension")]
    [InverseProperty("Chassisbonus")]
    public virtual Extension ExtensionNavigation { get; set; }

    [ForeignKey("TargetpropertyId")]
    [InverseProperty("Chassisbonus")]
    public virtual Aggregatefield Targetproperty { get; set; }
}