// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("cmails")]
[Index("Mailid", "Sourceid", Name = "IX_cmails_ids")]
public partial class Cmail
{
    [Column("owner")]
    public int Owner { get; set; }

    [Column("sender")]
    public int Sender { get; set; }

    [Column("target")]
    public int Target { get; set; }

    [Required]
    [Column("subject")]
    [StringLength(128)]
    public string Subject { get; set; }

    [Required]
    [Column("body")]
    [StringLength(2000)]
    public string Body { get; set; }

    [Column("type")]
    public byte Type { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("wasread")]
    public bool Wasread { get; set; }

    [Column("folder")]
    public byte Folder { get; set; }

    [Column("mailid")]
    public Guid? Mailid { get; set; }

    [Column("sourceid")]
    public Guid? Sourceid { get; set; }
}