// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("components")]
[Index("Definition", "Componentdefinition", Name = "IX_components", IsUnique = true)]
public partial class Component
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("componentdefinition")]
    public int Componentdefinition { get; set; }

    [Column("componentamount")]
    public int Componentamount { get; set; }

    [ForeignKey("Componentdefinition")]
    [InverseProperty("ComponentComponentdefinitionNavigations")]
    public virtual Entitydefault ComponentdefinitionNavigation { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("ComponentDefinitionNavigations")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}