// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("connectedips")]
[Index("Ipaddress", Name = "IX_connectedips")]
public partial class Connectedip
{
    [Required]
    [Column("ipaddress")]
    [StringLength(16)]
    [Unicode(false)]
    public string Ipaddress { get; set; }

    [Column("sessionstart", TypeName = "smalldatetime")]
    public DateTime Sessionstart { get; set; }

    [Column("banned")]
    public bool Banned { get; set; }

    [Column("note")]
    [StringLength(512)]
    public string Note { get; set; }

    [Column("bantime", TypeName = "smalldatetime")]
    public DateTime? Bantime { get; set; }

    /// <summary>
    /// just extra data: the character who put the ban on
    /// </summary>
    [Column("bannedby")]
    public int? Bannedby { get; set; }

    [Column("clientid")]
    public int Clientid { get; set; }

    [Column("accountid")]
    public int? Accountid { get; set; }
}