// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("corporations")]
[Index("Nick", Name = "IX_corporations_nick", IsUnique = true)]
[Index("Name", "Defaultcorp", Name = "IX_migration", IsUnique = true)]
public partial class Corporation
{
    /// <summary>
    /// unique index of a company entity - AZERT NULL mert az MCPbol lehet kell csinalni a defaultot
    /// </summary>
    [Key]
    [Column("eid")]
    public long Eid { get; set; }

    /// <summary>
    /// name of the company
    /// </summary>
    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("nick")]
    [StringLength(6)]
    [Unicode(false)]
    public string Nick { get; set; }

    /// <summary>
    /// asset value sum &gt; compute it!!!!
    /// </summary>
    [Column("wallet")]
    public double Wallet { get; set; }

    [Column("taxrate")]
    public int Taxrate { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("defaultcorp")]
    public bool Defaultcorp { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    /// <summary>
    /// characterID of the founder
    /// </summary>
    [Column("founder")]
    public int? Founder { get; set; }

    [Column("publicprofile")]
    public string Publicprofile { get; set; }

    [Column("privateprofile")]
    public string Privateprofile { get; set; }

    [Column("color")]
    public int? Color { get; set; }

    [InverseProperty("CorporationE")]
    public virtual ICollection<Corporationhistory> Corporationhistories { get; set; } = new List<Corporationhistory>();

    [InverseProperty("CorporationE")]
    public virtual ICollection<Corporationmember> Corporationmembers { get; set; } = new List<Corporationmember>();

    [InverseProperty("CorporationE")]
    public virtual CwCorporation CwCorporation { get; set; }

    [InverseProperty("Corporatione")]
    public virtual ICollection<Missionrequiredstanding> Missionrequiredstandings { get; set; } = new List<Missionrequiredstanding>();
}