// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("corporationleave")]
public partial class Corporationleave
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("leavetime", TypeName = "datetime")]
    public DateTime Leavetime { get; set; }
}