// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("corporationdocuments")]
public partial class Corporationdocument
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("lastmodified", TypeName = "datetime")]
    public DateTime Lastmodified { get; set; }

    [Column("validuntil", TypeName = "datetime")]
    public DateTime? Validuntil { get; set; }

    [Column("ownercharacterid")]
    public int Ownercharacterid { get; set; }

    [Column("documenttype")]
    public int Documenttype { get; set; }

    [Column("version")]
    public int Version { get; set; }

    [Column("body")]
    public string Body { get; set; }
}