// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("corporationApplication")]
public partial class CorporationApplication
{
    [Column("characterID")]
    public int CharacterId { get; set; }

    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("applyTime", TypeName = "smalldatetime")]
    public DateTime ApplyTime { get; set; }

    [Column("motivation")]
    [StringLength(512)]
    public string Motivation { get; set; }

    [ForeignKey("CorporationEid")]
    public virtual Corporation CorporationE { get; set; }
}