// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("corporationlog")]
[Index("CorporationEid", Name = "IX_corporationlogEID")]
public partial class Corporationlog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("timestamp", TypeName = "datetime")]
    public DateTime Timestamp { get; set; }

    [Column("corporationEid")]
    public long CorporationEid { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("issuerId")]
    public int IssuerId { get; set; }

    [Column("memberId")]
    public int MemberId { get; set; }
}