// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("corporationceotakeover")]
public partial class Corporationceotakeover
{
    [Column("corporationeid")]
    public long Corporationeid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("expiry", TypeName = "datetime")]
    public DateTime Expiry { get; set; }
}