// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("cw_spark_extension")]
[Index("Sparkid", "Extensionid", Name = "IX_cw_spark_extension", IsUnique = true)]
public partial class CwSparkExtension
{
    [Column("spark_extension_id")]
    public int SparkExtensionId { get; set; }

    [Column("sparkid")]
    public int Sparkid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("levelincrement")]
    public int Levelincrement { get; set; }

    [ForeignKey("Extensionid")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Sparkid")]
    public virtual CwSpark Spark { get; set; }
}