// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("decorcategories")]
[Index("Categoryname", Name = "IX_decorcategories", IsUnique = true)]
public partial class Decorcategory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("categoryname")]
    [StringLength(256)]
    [Unicode(false)]
    public string Categoryname { get; set; }

    [InverseProperty("CategoryNavigation")]
    public virtual ICollection<Decor> Decors { get; set; } = new List<Decor>();
}