// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("defaultfieldscalculation")]
public partial class Defaultfieldscalculation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("fieldname")]
    [StringLength(50)]
    public string Fieldname { get; set; }

    [Column("formula")]
    public int Formula { get; set; }

    [Column("display")]
    public bool Display { get; set; }

    [Column("runtime")]
    public bool Runtime { get; set; }
}