// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("definitionconfigunits")]
[Index("Configname", Name = "IX_definitionconfigunits", IsUnique = true)]
public partial class Definitionconfigunit
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("configname")]
    [StringLength(128)]
    [Unicode(false)]
    public string Configname { get; set; }

    [Column("measurementoffset")]
    public double Measurementoffset { get; set; }

    [Column("measurementmultiplier")]
    public double Measurementmultiplier { get; set; }

    [Column("digits")]
    public int Digits { get; set; }
}