// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("dynamiccalibrationtemplates")]
public partial class Dynamiccalibrationtemplate
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("materialefficiency")]
    public double Materialefficiency { get; set; }

    [Column("timeefficiency")]
    public double Timeefficiency { get; set; }

    [Column("targetdefinition")]
    public int Targetdefinition { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("DynamiccalibrationtemplateDefinitionNavigations")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Targetdefinition")]
    [InverseProperty("DynamiccalibrationtemplateTargetdefinitionNavigations")]
    public virtual Entitydefault TargetdefinitionNavigation { get; set; }
}