// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("effects")]
[Index("Name", Name = "IX_effects", IsUnique = true)]
public partial class Effect
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("effectcategory")]
    public long Effectcategory { get; set; }

    [Column("duration")]
    public int Duration { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    [StringLength(2048)]
    public string Description { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [Column("isaura")]
    public bool Isaura { get; set; }

    [Column("auraradius")]
    public int Auraradius { get; set; }

    [Column("ispositive")]
    public bool Ispositive { get; set; }

    [Column("display")]
    public int Display { get; set; }

    [Column("saveable")]
    public bool Saveable { get; set; }
}