// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("effectcategories")]
[Index("Name", Name = "IX_effectcategories", IsUnique = true)]
public partial class Effectcategory
{
    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Key]
    [Column("flag")]
    public long Flag { get; set; }

    [Column("maxlevel")]
    public int Maxlevel { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }
}