// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("entitydefaults")]
[Index("Categoryflags", Name = "IX_entitydefaults_cf")]
[Index("Definitionname", Name = "IX_entitydefaults_name", IsUnique = true)]
public partial class Entitydefault
{
    [Key]
    [Column("definition")]
    public int Definition { get; set; }

    [Required]
    [Column("definitionname")]
    [StringLength(100)]
    [Unicode(false)]
    public string Definitionname { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("attributeflags")]
    public long Attributeflags { get; set; }

    [Column("categoryflags")]
    public long Categoryflags { get; set; }

    [Column("options")]
    [Unicode(false)]
    public string Options { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [Column("volume")]
    public double? Volume { get; set; }

    [Column("mass")]
    public double? Mass { get; set; }

    [Column("hidden")]
    public bool Hidden { get; set; }

    [Column("health")]
    public double Health { get; set; }

    [Column("descriptiontoken")]
    [StringLength(100)]
    public string Descriptiontoken { get; set; }

    /// <summary>
    /// megjelenik-e a marketlistaban
    /// </summary>
    [Column("purchasable")]
    public bool Purchasable { get; set; }

    [Column("tiertype")]
    public int? Tiertype { get; set; }

    [Column("tierlevel")]
    public int? Tierlevel { get; set; }

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Aggregatevalue> Aggregatevalues { get; set; } = new List<Aggregatevalue>();

    [InverseProperty("DefinitionNavigation")]
    public virtual Beamassignment Beamassignment { get; set; }

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Chassisbonu> Chassisbonus { get; set; } = new List<Chassisbonu>();

    [InverseProperty("ComponentdefinitionNavigation")]
    public virtual ICollection<Component> ComponentComponentdefinitionNavigations { get; set; } = new List<Component>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Component> ComponentDefinitionNavigations { get; set; } = new List<Component>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Decor> Decors { get; set; } = new List<Decor>();

    [InverseProperty("DefinitionNavigation")]
    public virtual Definitionconfig Definitionconfig { get; set; }

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Dynamiccalibrationtemplate> DynamiccalibrationtemplateDefinitionNavigations { get; set; } = new List<Dynamiccalibrationtemplate>();

    [InverseProperty("TargetdefinitionNavigation")]
    public virtual ICollection<Dynamiccalibrationtemplate> DynamiccalibrationtemplateTargetdefinitionNavigations { get; set; } = new List<Dynamiccalibrationtemplate>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Enablerextension> Enablerextensions { get; set; } = new List<Enablerextension>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Giftloot> Giftloots { get; set; } = new List<Giftloot>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Insuranceprice> Insuranceprices { get; set; } = new List<Insuranceprice>();

    [InverseProperty("ItemdefinitionNavigation")]
    public virtual ICollection<Intrusionloot> IntrusionlootItemdefinitionNavigations { get; set; } = new List<Intrusionloot>();

    [InverseProperty("SapdefinitionNavigation")]
    public virtual ICollection<Intrusionloot> IntrusionlootSapdefinitionNavigations { get; set; } = new List<Intrusionloot>();

    [InverseProperty("SitedefinitionNavigation")]
    public virtual ICollection<Intrusionloot> IntrusionlootSitedefinitionNavigations { get; set; } = new List<Intrusionloot>();

    [InverseProperty("CalibrationprogramNavigation")]
    public virtual ICollection<Itemresearchlevel> ItemresearchlevelCalibrationprogramNavigations { get; set; } = new List<Itemresearchlevel>();

    [InverseProperty("DefinitionNavigation")]
    public virtual Itemresearchlevel ItemresearchlevelDefinitionNavigation { get; set; }

    [InverseProperty("TargetdefinitionNavigation")]
    public virtual ICollection<Itemshop> Itemshops { get; set; } = new List<Itemshop>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Missionreward> Missionrewards { get; set; } = new List<Missionreward>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Missionstartitem> Missionstartitems { get; set; } = new List<Missionstartitem>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Missiontarget> Missiontargets { get; set; } = new List<Missiontarget>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Npccontaineritem> NpccontaineritemDefinitionNavigations { get; set; } = new List<Npccontaineritem>();

    [InverseProperty("LootdefinitionNavigation")]
    public virtual ICollection<Npccontaineritem> NpccontaineritemLootdefinitionNavigations { get; set; } = new List<Npccontaineritem>();

    [InverseProperty("LootdefinitionNavigation")]
    public virtual ICollection<Npcflockloot> Npcflockloots { get; set; } = new List<Npcflockloot>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Npcflock> Npcflocks { get; set; } = new List<Npcflock>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Npcloot> NpclootDefinitionNavigations { get; set; } = new List<Npcloot>();

    [InverseProperty("LootdefinitionNavigation")]
    public virtual ICollection<Npcloot> NpclootLootdefinitionNavigations { get; set; } = new List<Npcloot>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Nspoolmember> Nspoolmembers { get; set; } = new List<Nspoolmember>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Nstemplate> Nstemplates { get; set; } = new List<Nstemplate>();

    [InverseProperty("DefinitionNavigation")]
    public virtual Plantdamagetype Plantdamagetype { get; set; }

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Prototype> PrototypeDefinitionNavigations { get; set; } = new List<Prototype>();

    [InverseProperty("Prototype1Navigation")]
    public virtual ICollection<Prototype> PrototypePrototype1Navigations { get; set; } = new List<Prototype>();

    [InverseProperty("ChassisNavigation")]
    public virtual ICollection<Robotsetup> RobotsetupChassisNavigations { get; set; } = new List<Robotsetup>();

    [InverseProperty("ContainerNavigation")]
    public virtual ICollection<Robotsetup> RobotsetupContainerNavigations { get; set; } = new List<Robotsetup>();

    [InverseProperty("HeadNavigation")]
    public virtual ICollection<Robotsetup> RobotsetupHeadNavigations { get; set; } = new List<Robotsetup>();

    [InverseProperty("HybridshellNavigation")]
    public virtual ICollection<Robotsetup> RobotsetupHybridshellNavigations { get; set; } = new List<Robotsetup>();

    [InverseProperty("LegNavigation")]
    public virtual ICollection<Robotsetup> RobotsetupLegNavigations { get; set; } = new List<Robotsetup>();

    [InverseProperty("RobotshellNavigation")]
    public virtual ICollection<Robotsetup> RobotsetupRobotshellNavigations { get; set; } = new List<Robotsetup>();

    [InverseProperty("DefinitionNavigation")]
    public virtual Robottemplaterelation Robottemplaterelation { get; set; }

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Siegeitem> Siegeitems { get; set; } = new List<Siegeitem>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Storeitem> Storeitems { get; set; } = new List<Storeitem>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Techlineincrement> Techlineincrements { get; set; } = new List<Techlineincrement>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Techlinemember> Techlinemembers { get; set; } = new List<Techlinemember>();

    [InverseProperty("DefinitionNavigation")]
    public virtual ICollection<Vendorpresetvalue> Vendorpresetvalues { get; set; } = new List<Vendorpresetvalue>();
}