// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("entitystorage")]
[Index("StorageName", Name = "IX_entitystorage", IsUnique = true)]
public partial class Entitystorage
{
    [Required]
    [Column("storage_name")]
    [StringLength(50)]
    public string StorageName { get; set; }

    [Column("eid")]
    public long? Eid { get; set; }
}