// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("entities")]
[Index("Definition", "Owner", Name = "IX_def_owner")]
[Index("Owner", Name = "itemcounterIX")]
public partial class Entity
{
    [Key]
    [Column("eid")]
    public long Eid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }

    [Column("parent")]
    public long? Parent { get; set; }

    [Column("health")]
    public double Health { get; set; }

    [Column("ename")]
    [StringLength(128)]
    public string Ename { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("repackaged")]
    public bool Repackaged { get; set; }

    [Column("dynprop")]
    [Unicode(false)]
    public string Dynprop { get; set; }
}