// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("environmentdescriptionstaging")]
[Index("Definition", Name = "IX_environmentdescriptionstaging", IsUnique = true)]
public partial class Environmentdescriptionstaging
{
    [Column("definition")]
    public int Definition { get; set; }

    [Required]
    [Column("descriptionstring")]
    [Unicode(false)]
    public string Descriptionstring { get; set; }

    [ForeignKey("Definition")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}