// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("epforactivitylog")]
public partial class Epforactivitylog
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("epforactivitytype")]
    public int Epforactivitytype { get; set; }

    [Column("rawpoints")]
    public int Rawpoints { get; set; }

    [Column("points")]
    public int Points { get; set; }

    [Column("boostfactor")]
    public double Boostfactor { get; set; }

    [Column("multiplier")]
    public int? Multiplier { get; set; }

    [Column("bonusMultiplier")]
    public int? BonusMultiplier { get; set; }
}