// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("extensions")]
[Index("Extensionname", Name = "IX_extensions_name", IsUnique = true)]
public partial class Extension
{
    [Key]
    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Required]
    [Column("extensionname")]
    [StringLength(128)]
    [Unicode(false)]
    public string Extensionname { get; set; }

    [Column("category")]
    public int Category { get; set; }

    [Column("rank")]
    public int Rank { get; set; }

    [Column("targetlearningattribute")]
    [StringLength(50)]
    [Unicode(false)]
    public string Targetlearningattribute { get; set; }

    [Required]
    [Column("learningattributeprimary")]
    [StringLength(50)]
    [Unicode(false)]
    public string Learningattributeprimary { get; set; }

    [Column("learningattributesecondary")]
    [StringLength(50)]
    [Unicode(false)]
    public string Learningattributesecondary { get; set; }

    [Column("bonus")]
    public double Bonus { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [Column("price")]
    public int Price { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Column("description")]
    [StringLength(128)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("targetpropertyID")]
    public int? TargetpropertyId { get; set; }

    [Column("effectenhancer")]
    public bool Effectenhancer { get; set; }

    [Column("hidden")]
    public bool Hidden { get; set; }

    [Column("freezelimit")]
    public int? Freezelimit { get; set; }

    [ForeignKey("Category")]
    [InverseProperty("Extensions")]
    public virtual Extensioncategory CategoryNavigation { get; set; }

    [InverseProperty("Extension")]
    public virtual ICollection<Characterextension> Characterextensions { get; set; } = new List<Characterextension>();

    [InverseProperty("ExtensionNavigation")]
    public virtual ICollection<Chassisbonu> Chassisbonus { get; set; } = new List<Chassisbonu>();

    [InverseProperty("Extension")]
    public virtual ICollection<CwCorporationExtension> CwCorporationExtensions { get; set; } = new List<CwCorporationExtension>();

    [InverseProperty("Extension")]
    public virtual ICollection<Enablerextension> Enablerextensions { get; set; } = new List<Enablerextension>();

    [InverseProperty("Extension")]
    public virtual ICollection<Missionrequiredextension> Missionrequiredextensions { get; set; } = new List<Missionrequiredextension>();

    [InverseProperty("Extension")]
    public virtual ICollection<Sparkextension> Sparkextensions { get; set; } = new List<Sparkextension>();

    [ForeignKey("TargetpropertyId")]
    [InverseProperty("Extensions")]
    public virtual Aggregatefield Targetproperty { get; set; }
}