// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("extensionpointworklog")]
public partial class Extensionpointworklog
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("total")]
    public int Total { get; set; }

    [Column("paying")]
    public int Paying { get; set; }

    [Column("id")]
    public int Id { get; set; }
}