// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("extensionpointpenalty")]
public partial class Extensionpointpenalty
{
    [Column("id")]
    public int Id { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("points")]
    public int Points { get; set; }

    [Column("penaltytype")]
    public int Penaltytype { get; set; }

    [Column("forever")]
    public bool Forever { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }
}