// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("extensionsubscription")]
public partial class Extensionsubscription
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("starttime", TypeName = "datetime")]
    public DateTime Starttime { get; set; }

    [Column("endtime", TypeName = "datetime")]
    public DateTime Endtime { get; set; }

    [Column("multiplierBonus")]
    public int MultiplierBonus { get; set; }
}