// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("gangmembers")]
[Index("Memberid", Name = "IX_gangmembers_1")]
public partial class Gangmember
{
    [Column("gangid")]
    public Guid Gangid { get; set; }

    [Column("memberid")]
    public int Memberid { get; set; }

    [Column("role")]
    public int Role { get; set; }

    [ForeignKey("Gangid")]
    public virtual Gang Gang { get; set; }
}