// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("hostconfig")]
[Index("Sequenceid", Name = "IX_hostconfig", IsUnique = true)]
public partial class Hostconfig
{
    [Required]
    [Column("hostname")]
    [StringLength(50)]
    [Unicode(false)]
    public string Hostname { get; set; }

    [Required]
    [Column("hostip")]
    [StringLength(50)]
    [Unicode(false)]
    public string Hostip { get; set; }

    [Column("hostport")]
    public int Hostport { get; set; }

    [Column("sequenceid")]
    public int Sequenceid { get; set; }

    [Column("monitor")]
    public bool Monitor { get; set; }
}