// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("insuranceprices")]
public partial class Insuranceprice
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("fee")]
    public double Fee { get; set; }

    [Column("payout")]
    public double Payout { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Insuranceprices")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}