// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("intrusionsites")]
public partial class Intrusionsite
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [Column("stability")]
    public int Stability { get; set; }

    [Column("dockingstandinglimit")]
    public double? Dockingstandinglimit { get; set; }

    [Column("dockingcontroltime", TypeName = "datetime")]
    public DateTime? Dockingcontroltime { get; set; }

    [Column("seteffectcontroltime", TypeName = "datetime")]
    public DateTime? Seteffectcontroltime { get; set; }

    [Column("activeeffectid")]
    public int? Activeeffectid { get; set; }

    [Column("message")]
    [StringLength(256)]
    public string Message { get; set; }

    [Column("productionpoints")]
    public int Productionpoints { get; set; }

    [Column("intrusionstarttime", TypeName = "datetime")]
    public DateTime? Intrusionstarttime { get; set; }

    [Column("defensestandinglimit")]
    public double? Defensestandinglimit { get; set; }

    [Column("note")]
    [StringLength(128)]
    [Unicode(false)]
    public string Note { get; set; }
}