// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("intrusionloot")]
public partial class Intrusionloot
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("sitedefinition")]
    public int Sitedefinition { get; set; }

    [Column("sapdefinition")]
    public int Sapdefinition { get; set; }

    [Column("itemdefinition")]
    public int Itemdefinition { get; set; }

    [Column("minquantity")]
    public int Minquantity { get; set; }

    [Column("maxquantity")]
    public int Maxquantity { get; set; }

    [Column("minstabilitythreshold")]
    public int Minstabilitythreshold { get; set; }

    [Column("maxstabilitythreshold")]
    public int Maxstabilitythreshold { get; set; }

    [Column("probability")]
    public double Probability { get; set; }

    [ForeignKey("Itemdefinition")]
    [InverseProperty("IntrusionlootItemdefinitionNavigations")]
    public virtual Entitydefault ItemdefinitionNavigation { get; set; }

    [ForeignKey("Sapdefinition")]
    [InverseProperty("IntrusionlootSapdefinitionNavigations")]
    public virtual Entitydefault SapdefinitionNavigation { get; set; }

    [ForeignKey("Sitedefinition")]
    [InverseProperty("IntrusionlootSitedefinitionNavigations")]
    public virtual Entitydefault SitedefinitionNavigation { get; set; }
}