// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("itemprices")]
public partial class Itemprice
{
    [Column("definition")]
    public int Definition { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [Column("profitrate")]
    public double Profitrate { get; set; }

    [Column("manualprice")]
    public bool Manualprice { get; set; }

    [ForeignKey("Definition")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}