// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("itemresearchlevels")]
[Index("Definition", Name = "IX_itemresearchlevels", IsUnique = true)]
public partial class Itemresearchlevel
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("researchlevel")]
    public int Researchlevel { get; set; }

    [Column("calibrationprogram")]
    public int? Calibrationprogram { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [ForeignKey("Calibrationprogram")]
    [InverseProperty("ItemresearchlevelCalibrationprogramNavigations")]
    public virtual Entitydefault CalibrationprogramNavigation { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("ItemresearchlevelDefinitionNavigation")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}