// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("killreports")]
[Index("Date", Name = "IX_killreports", AllDescending = true)]
public partial class Killreport
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("date", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("data")]
    [Unicode(false)]
    public string Data { get; set; }
}