// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("marketaverageprices")]
[Index("Itemdefinition", "Date", Name = "avgprices_ixx")]
public partial class Marketaverageprice
{
    [Column("marketeid")]
    public long Marketeid { get; set; }

    [Column("itemdefinition")]
    public int Itemdefinition { get; set; }

    [Column("totalprice")]
    public double Totalprice { get; set; }

    [Column("quantity")]
    public long Quantity { get; set; }

    [Column("date", TypeName = "smalldatetime")]
    public DateTime Date { get; set; }

    [Column("dailylowest")]
    public double Dailylowest { get; set; }

    [Column("dailyhighest")]
    public double Dailyhighest { get; set; }
}