// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missiontypes")]
public partial class Missiontype
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("category")]
    [StringLength(50)]
    [Unicode(false)]
    public string Category { get; set; }

    [Column("categoryvalue")]
    public int Categoryvalue { get; set; }

    [InverseProperty("MissiontypeNavigation")]
    public virtual ICollection<Mission> Missions { get; set; } = new List<Mission>();
}