// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missionspotinfo")]
public partial class Missionspotinfo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }
}