// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missionenterpoints")]
public partial class Missionenterpoint
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("teleportchannelid")]
    public int Teleportchannelid { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [ForeignKey("Missionid")]
    [InverseProperty("Missionenterpoints")]
    public virtual Mission Mission { get; set; }

    [ForeignKey("Teleportchannelid")]
    [InverseProperty("Missionenterpoints")]
    public virtual Teleportdescription Teleportchannel { get; set; }
}