// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("missiontargetsarchive")]
public partial class Missiontargetsarchive
{
    [Column("missionid")]
    public int Missionid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("targetid")]
    public int Targetid { get; set; }

    [Column("progresscount")]
    public int Progresscount { get; set; }

    [Column("completed")]
    public bool Completed { get; set; }

    [Column("missionguid")]
    public Guid Missionguid { get; set; }

    [Column("targetorder")]
    public int? Targetorder { get; set; }

    [Column("displayorder")]
    public int? Displayorder { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("structureeid")]
    public long? Structureeid { get; set; }

    [Column("secondarydefinition")]
    public int? Secondarydefinition { get; set; }

    [Column("secondaryquantity")]
    public int? Secondaryquantity { get; set; }

    [Column("zoneid")]
    public int? Zoneid { get; set; }

    [Column("x")]
    public int? X { get; set; }

    [Column("y")]
    public int? Y { get; set; }

    [Column("artifacttype")]
    public int? Artifacttype { get; set; }

    [Column("targettype")]
    public int? Targettype { get; set; }

    [Column("scantype")]
    public int? Scantype { get; set; }

    [Column("targetrange")]
    public int? Targetrange { get; set; }

    [Column("successx")]
    public int? Successx { get; set; }

    [Column("successy")]
    public int? Successy { get; set; }

    [Column("successzoneid")]
    public int? Successzoneid { get; set; }

    [Column("successtime", TypeName = "datetime")]
    public DateTime? Successtime { get; set; }

    [ForeignKey("Missionguid")]
    public virtual Missionlog Mission { get; set; }
}