// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missionrequiredstanding")]
[Index("Corporationeid", "Missionid", Name = "IX_missionrequiredstanding", IsUnique = true)]
public partial class Missionrequiredstanding
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [Column("corporationeid")]
    public long? Corporationeid { get; set; }

    [Column("standingabove")]
    public bool Standingabove { get; set; }

    [Column("standingthreshold")]
    public double Standingthreshold { get; set; }

    [Column("corporationname")]
    [StringLength(128)]
    [Unicode(false)]
    public string Corporationname { get; set; }

    [ForeignKey("Corporationeid")]
    [InverseProperty("Missionrequiredstandings")]
    public virtual Corporation Corporatione { get; set; }

    [ForeignKey("Missionid")]
    [InverseProperty("Missionrequiredstandings")]
    public virtual Mission Mission { get; set; }
}