// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missionstandingchange")]
public partial class Missionstandingchange
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [Column("change")]
    public double Change { get; set; }

    [Column("alliancename")]
    [StringLength(50)]
    [Unicode(false)]
    public string Alliancename { get; set; }

    [Column("allianceeid")]
    public long? Allianceeid { get; set; }

    [ForeignKey("Missionid")]
    [InverseProperty("Missionstandingchanges")]
    public virtual Mission Mission { get; set; }
}