// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missionissuer")]
public partial class Missionissuer
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("corporationeid")]
    public long? Corporationeid { get; set; }

    [Column("corporationname")]
    [StringLength(60)]
    [Unicode(false)]
    public string Corporationname { get; set; }

    [Column("allianceeid")]
    public long? Allianceeid { get; set; }

    [Column("alliancename")]
    [StringLength(60)]
    [Unicode(false)]
    public string Alliancename { get; set; }

    [InverseProperty("Issuer")]
    public virtual ICollection<Mission> Missions { get; set; } = new List<Mission>();
}