// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missiongrind")]
public partial class Missiongrind
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("missionlevel")]
    public int Missionlevel { get; set; }

    [Column("amount")]
    public int Amount { get; set; }
}