// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("missionbonus")]
public partial class Missionbonu
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("missioncategory")]
    public int Missioncategory { get; set; }

    [Column("missionlevel")]
    public int Missionlevel { get; set; }

    [Column("agentid")]
    public int Agentid { get; set; }

    [Column("bonus")]
    public int Bonus { get; set; }
}