// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("missiontargetslog")]
public partial class Missiontargetslog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }

    [Column("targettype")]
    public int Targettype { get; set; }

    [Column("guid")]
    public Guid Guid { get; set; }

    [Column("locationeid")]
    public long Locationeid { get; set; }

    [Column("missioncategory")]
    public int Missioncategory { get; set; }
}