// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("npcflock")]
public partial class Npcflock
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("presenceid")]
    public int Presenceid { get; set; }

    /// <summary>
    /// Flock NPCs present in zone at the same time
    /// </summary>
    [Column("flockmembercount")]
    public int Flockmembercount { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("spawnoriginX")]
    public int SpawnoriginX { get; set; }

    [Column("spawnoriginY")]
    public int SpawnoriginY { get; set; }

    [Column("spawnrangeMin")]
    public int SpawnrangeMin { get; set; }

    [Column("spawnrangeMax")]
    public int SpawnrangeMax { get; set; }

    [Column("respawnseconds")]
    public int Respawnseconds { get; set; }

    /// <summary>
    /// 0 = respawn forever -&gt; amount of npcs will be spawned
    /// </summary>
    [Column("totalspawncount")]
    public int Totalspawncount { get; set; }

    [Column("homerange")]
    public int Homerange { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("respawnmultiplierlow")]
    public double Respawnmultiplierlow { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [Column("iscallforhelp")]
    public bool Iscallforhelp { get; set; }

    [Column("behaviorType")]
    public int BehaviorType { get; set; }

    [Column("npcSpecialType")]
    public int NpcSpecialType { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Npcflocks")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [InverseProperty("Flock")]
    public virtual ICollection<Npcflockloot> Npcflockloots { get; set; } = new List<Npcflockloot>();

    [InverseProperty("Flock")]
    public virtual ICollection<Npcpoolpresetvalue> Npcpoolpresetvalues { get; set; } = new List<Npcpoolpresetvalue>();

    [ForeignKey("Presenceid")]
    [InverseProperty("Npcflocks")]
    public virtual Npcpresence Presence { get; set; }
}