// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("npcflockloot")]
[Index("Lootdefinition", "Flockid", Name = "IX_npcflockloot", IsUnique = true)]
public partial class Npcflockloot
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("flockid")]
    public int Flockid { get; set; }

    [Column("lootdefinition")]
    public int Lootdefinition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("probability")]
    public double Probability { get; set; }

    [Column("repackaged")]
    public bool Repackaged { get; set; }

    [Column("dontdamage")]
    public bool Dontdamage { get; set; }

    [Column("minquantity")]
    public int Minquantity { get; set; }

    [ForeignKey("Flockid")]
    [InverseProperty("Npcflockloots")]
    public virtual Npcflock Flock { get; set; }

    [ForeignKey("Lootdefinition")]
    [InverseProperty("Npcflockloots")]
    public virtual Entitydefault LootdefinitionNavigation { get; set; }
}