// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("npcpoolpresetvalues")]
public partial class Npcpoolpresetvalue
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("presetid")]
    public int Presetid { get; set; }

    [Column("flockid")]
    public int Flockid { get; set; }

    [Column("rate")]
    public double Rate { get; set; }

    [ForeignKey("Flockid")]
    [InverseProperty("Npcpoolpresetvalues")]
    public virtual Npcflock Flock { get; set; }

    [ForeignKey("Presetid")]
    [InverseProperty("Npcpoolpresetvalues")]
    public virtual Npcpoolpreset Preset { get; set; }
}