// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("npcrandomflockpool")]
public partial class Npcrandomflockpool
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("presenceid")]
    public int Presenceid { get; set; }

    [Column("flockid")]
    public int Flockid { get; set; }

    [Column("rate")]
    public double Rate { get; set; }

    [Column("lastwave")]
    public bool Lastwave { get; set; }
}