// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("npcreinforcements")]
public partial class Npcreinforcement
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("reinforcementType")]
    public int ReinforcementType { get; set; }

    [Column("targetId")]
    public int TargetId { get; set; }

    [Column("threshold")]
    public double Threshold { get; set; }

    [Column("presenceId")]
    public int PresenceId { get; set; }

    [Column("zoneId")]
    public int? ZoneId { get; set; }
}