// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("nspoolrelation")]
[Index("Sourcepool", "Targetpool", Name = "IX_nspoolrelation", IsUnique = true)]
public partial class Nspoolrelation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("sourcepool")]
    public int Sourcepool { get; set; }

    [Column("targetpool")]
    public int Targetpool { get; set; }

    [ForeignKey("Sourcepool")]
    [InverseProperty("NspoolrelationSourcepoolNavigations")]
    public virtual Nspool SourcepoolNavigation { get; set; }

    [ForeignKey("Targetpool")]
    [InverseProperty("NspoolrelationTargetpoolNavigations")]
    public virtual Nspool TargetpoolNavigation { get; set; }
}