// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("ownerincome")]
public partial class Ownerincome
{
    [Column("corporationeid")]
    public long Corporationeid { get; set; }

    [Column("amount")]
    public double Amount { get; set; }

    [Column("lastflush", TypeName = "smalldatetime")]
    public DateTime Lastflush { get; set; }
}