// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("packageitems")]
public partial class Packageitem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("packageid")]
    public int Packageid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [ForeignKey("Packageid")]
    [InverseProperty("Packageitems")]
    public virtual Package Package { get; set; }
}