// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("paypal_transactions_history")]
public partial class PaypalTransactionsHistory
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    /// <summary>
    /// Unique transaction ID of the payment. Note:  If the PaymentAction of the request was Authorization or Order, this value is your AuthorizationID for use with the Authorization &amp; Capture APIs.
    /// </summary>
    [Required]
    [Column("transactionID")]
    [StringLength(32)]
    public string TransactionId { get; set; }

    /// <summary>
    /// The type of transaction Possible values: l 0=cart l 1=express-checkout
    /// </summary>
    [Required]
    [Column("transactionType")]
    [StringLength(50)]
    public string TransactionType { get; set; }

    /// <summary>
    /// Indicates whether the payment is instant or delayed. Possible values: l  0=none l 1= echeck l 2= instant 
    /// </summary>
    [Required]
    [Column("paymentType")]
    [StringLength(50)]
    public string PaymentType { get; set; }

    /// <summary>
    /// Time/date stamp of payment
    /// </summary>
    [Column("orderTime", TypeName = "datetime")]
    public DateTime OrderTime { get; set; }

    /// <summary>
    /// The final amount charged, including any shipping and taxes from your Merchant Profile.
    /// </summary>
    [Column("amt")]
    public double Amt { get; set; }

    /// <summary>
    /// A three-character currency code for one of the currencies listed in PayPay-Supported Transactional Currencies. Default: USD. 
    /// </summary>
    [Required]
    [Column("currencyCode")]
    [StringLength(3)]
    public string CurrencyCode { get; set; }

    /// <summary>
    /// PayPal fee amount charged for the transaction
    /// </summary>
    [Column("feeAmt")]
    public double FeeAmt { get; set; }

    /// <summary>
    /// Amount deposited in your PayPal account after a currency conversion.
    /// </summary>
    [Column("settleAmt")]
    public double SettleAmt { get; set; }

    /// <summary>
    /// Tax charged on the transaction.
    /// </summary>
    [Column("taxAmt")]
    public double TaxAmt { get; set; }

    /// <summary>
    /// Exchange rate if a currency conversion occurred. Relevant only if your are billing in their non-primary currency. If the customer chooses to pay with a currency other than the non-primary currency, the conversion occurs in the customer’s account.
    /// </summary>
    [Column("exchangeRate")]
    public double? ExchangeRate { get; set; }

    /// <summary>
    /// Status of the payment:
    /// - Completed: The payment has been completed, and the funds have been added successfully to your account balance.
    /// 
    /// - Pending: The payment is pending. See the PendingReason element for more information. 
    /// 		
    /// </summary>
    [Column("paymentStatus")]
    [StringLength(50)]
    public string PaymentStatus { get; set; }

    /// <summary>
    /// The reason the payment is pending:
    /// 
    /// - none: No pending reason
    /// - address: The payment is pending because your customer did not include a confirmed shipping address and your Payment Receiving Preferences is set such that you want to manually accept or deny each of these payments. To change your preference, go to the Preferences section of your Profile.
    /// - echeck: The payment is pending because it was made by an eCheck that has not yet cleared.
    /// - intl: The payment is pending because you hold a non-U.S. account and do not have a withdrawal mechanism. You must manually accept or deny this payment from your Account Overview.
    /// - multi-currency: You do not have a balance in the currency sent, and you do not have your Payment Receiving Preferences set to automatically convert and accept this payment. You must manually accept or deny this payment.
    /// - verify: The payment is pending because you are not yet verified. You must verify your account before you can accept this payment. 
    /// - other: The payment is pending for a reason other than those listed above. For more information, contact PayPal customer service. 
    /// </summary>
    [Column("pendingReason")]
    [StringLength(50)]
    public string PendingReason { get; set; }

    /// <summary>
    /// The reason for a reversal if TransactionType is reversal:
    /// 		- none: No reason code
    /// - chargeback: A reversal has occurred on this transaction due to a chargeback by your customer.
    /// - guarantee: A reversal has occurred on this transaction due to your customer triggering a money-back guarantee.
    /// - buyer-complaint: A reversal has occurred on this transaction due to a complaint about the transaction from your customer. 
    /// - refund: A reversal has occurred on this transaction because you have given the customer a refund.
    /// - other: A reversal has occurred on this transaction due to a reason not listed above. 
    /// 		
    /// </summary>
    [Column("reasonCode")]
    [StringLength(50)]
    public string ReasonCode { get; set; }

    [Column("orderID")]
    public int OrderId { get; set; }
}