// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("pbsreimburse")]
public partial class Pbsreimburse
{
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("corporationeid")]
    public long? Corporationeid { get; set; }

    [Column("baseeid")]
    public long Baseeid { get; set; }
}