// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("plantrules")]
[Index("Plantrule1", "Rulesetid", Name = "IX_plantrules", IsUnique = true)]
public partial class Plantrule
{
    /// <summary>
    /// NOT THE PLANT INDEX
    /// </summary>
    [Key]
    [Column("idx")]
    public int Idx { get; set; }

    [Required]
    [Column("plantrule")]
    [StringLength(256)]
    [Unicode(false)]
    public string Plantrule1 { get; set; }

    [Column("rulesetid")]
    public int Rulesetid { get; set; }

    [Column("note")]
    [StringLength(1024)]
    public string Note { get; set; }
}