// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("plantdamagetype")]
[Index("Definition", Name = "IX_plantdamagetype", IsUnique = true)]
public partial class Plantdamagetype
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("plantdamagetype")]
    public int Plantdamagetype1 { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Plantdamagetype")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}