// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("productionduration")]
[Index("Category", Name = "IX_productionduration", IsUnique = true)]
public partial class Productionduration
{
    [Column("id")]
    public int Id { get; set; }

    [Column("category")]
    public long Category { get; set; }

    [Column("durationmodifier")]
    public double Durationmodifier { get; set; }

    [ForeignKey("Category")]
    public virtual CategoryFlag CategoryNavigation { get; set; }
}