// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("productiondecalibration")]
[Index("Categoryflag", Name = "IX_productiondecalibration_1", IsUnique = true)]
public partial class Productiondecalibration
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("categoryflag")]
    public long Categoryflag { get; set; }

    [Column("distorsionmin")]
    public double Distorsionmin { get; set; }

    [Column("distorsionmax")]
    public double Distorsionmax { get; set; }

    [Column("decrease")]
    public double? Decrease { get; set; }

    [ForeignKey("Categoryflag")]
    [InverseProperty("Productiondecalibration")]
    public virtual CategoryFlag CategoryflagNavigation { get; set; }
}