// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("prototypes")]
[Index("Definition", "Prototype1", Name = "IX_prototypes")]
public partial class Prototype
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("prototype")]
    public int Prototype1 { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("PrototypeDefinitionNavigations")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Prototype1")]
    [InverseProperty("PrototypePrototype1Navigations")]
    public virtual Entitydefault Prototype1Navigation { get; set; }
}