// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("rarematerials")]
public partial class Rarematerial
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("raredefinition")]
    public int Raredefinition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("chance")]
    public double Chance { get; set; }
}