// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("reimbursementlog")]
public partial class Reimbursementlog
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("targetaccountid")]
    public int Targetaccountid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("comment")]
    [StringLength(512)]
    [Unicode(false)]
    public string Comment { get; set; }

    [Column("wasinsured")]
    public bool Wasinsured { get; set; }

    [Column("killedbyplayer")]
    public bool Killedbyplayer { get; set; }

    [Column("inactiveperiod")]
    public int Inactiveperiod { get; set; }

    [Column("dctime", TypeName = "datetime")]
    public DateTime? Dctime { get; set; }

    [Column("deleted", TypeName = "datetime")]
    public DateTime? Deleted { get; set; }
}