// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("relays")]
[Index("Currentusers", Name = "IX_relays_currentusers")]
public partial class Relay
{
    [Required]
    [Column("relayname")]
    [StringLength(50)]
    [Unicode(false)]
    public string Relayname { get; set; }

    [Column("maxusers")]
    public int Maxusers { get; set; }

    [Column("currentusers")]
    public int Currentusers { get; set; }

    [Required]
    [Column("ipaddress")]
    [StringLength(32)]
    [Unicode(false)]
    public string Ipaddress { get; set; }

    [Column("port")]
    public int Port { get; set; }
}