// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("relictypes")]
public partial class Relictype
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("raceid")]
    public int? Raceid { get; set; }

    [Column("level")]
    public int? Level { get; set; }

    [Column("ep")]
    public int? Ep { get; set; }
}