// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("relicloot")]
public partial class Relicloot
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("minquantity")]
    public int Minquantity { get; set; }

    [Column("maxquantity")]
    public int Maxquantity { get; set; }

    [Column("chance", TypeName = "decimal(9, 6)")]
    public decimal Chance { get; set; }

    [Column("relictypeid")]
    public int Relictypeid { get; set; }

    [Column("packed")]
    public bool Packed { get; set; }
}