// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("reliczoneconfig")]
public partial class Reliczoneconfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("maxspawn")]
    public int Maxspawn { get; set; }

    [Column("respawnrate")]
    public int Respawnrate { get; set; }
}