// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("relicspawninfo")]
public partial class Relicspawninfo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("relictypeid")]
    public int Relictypeid { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("rate")]
    public int Rate { get; set; }

    [Column("x")]
    public int? X { get; set; }

    [Column("y")]
    public int? Y { get; set; }
}