// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("robottemplaterelation")]
[Index("Definition", "Templateid", Name = "IX_robottemplaterelation", IsUnique = true)]
public partial class Robottemplaterelation
{
    [Key]
    [Column("definition")]
    public int Definition { get; set; }

    [Column("templateid")]
    public int Templateid { get; set; }

    [Column("itemscoresum")]
    public int Itemscoresum { get; set; }

    [Column("raceid")]
    public int Raceid { get; set; }

    [Column("missionlevel")]
    public int? Missionlevel { get; set; }

    [Column("missionleveloverride")]
    public int? Missionleveloverride { get; set; }

    [Column("killep")]
    public int? Killep { get; set; }

    [Column("note")]
    [StringLength(256)]
    [Unicode(false)]
    public string Note { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Robottemplaterelation")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Templateid")]
    [InverseProperty("Robottemplaterelations")]
    public virtual Robottemplate Template { get; set; }
}