// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("robotfittingpresets")]
public partial class Robotfittingpreset
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("ownerEid")]
    public long OwnerEid { get; set; }

    [Required]
    [Column("preset")]
    [Unicode(false)]
    public string Preset { get; set; }
}