// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("robotassembler")]
[Index("Characterid", "Facilityeid", Name = "IX_robotassembler", IsUnique = true)]
public partial class Robotassembler
{
    /// <summary>
    /// EZ KELL A FASZNAK, kuldje be egybol
    /// </summary>
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("charactereid")]
    public long Charactereid { get; set; }

    [Column("facilityeid")]
    public long Facilityeid { get; set; }

    [Column("head")]
    public long? Head { get; set; }

    [Column("chassis")]
    public long? Chassis { get; set; }

    [Column("leg")]
    public long? Leg { get; set; }
}