// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("robottemplates")]
[Index("Name", Name = "IX_robottemplates_name", IsUnique = true)]
public partial class Robottemplate
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [InverseProperty("Template")]
    public virtual ICollection<Robottemplaterelation> Robottemplaterelations { get; set; } = new List<Robottemplaterelation>();
}