// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("robotsetup")]
public partial class Robotsetup
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("robotshell")]
    public int Robotshell { get; set; }

    [Column("head")]
    public int Head { get; set; }

    [Column("chassis")]
    public int Chassis { get; set; }

    [Column("leg")]
    public int Leg { get; set; }

    [Column("container")]
    public int Container { get; set; }

    [Column("hybridshell")]
    public int Hybridshell { get; set; }

    [ForeignKey("Chassis")]
    [InverseProperty("RobotsetupChassisNavigations")]
    public virtual Entitydefault ChassisNavigation { get; set; }

    [ForeignKey("Container")]
    [InverseProperty("RobotsetupContainerNavigations")]
    public virtual Entitydefault ContainerNavigation { get; set; }

    [ForeignKey("Head")]
    [InverseProperty("RobotsetupHeadNavigations")]
    public virtual Entitydefault HeadNavigation { get; set; }

    [ForeignKey("Hybridshell")]
    [InverseProperty("RobotsetupHybridshellNavigations")]
    public virtual Entitydefault HybridshellNavigation { get; set; }

    [ForeignKey("Leg")]
    [InverseProperty("RobotsetupLegNavigations")]
    public virtual Entitydefault LegNavigation { get; set; }

    [ForeignKey("Robotshell")]
    [InverseProperty("RobotsetupRobotshellNavigations")]
    public virtual Entitydefault RobotshellNavigation { get; set; }
}