// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("runningproductionreserveditem")]
public partial class Runningproductionreserveditem
{
    [Column("runningid")]
    public int Runningid { get; set; }

    [Column("reservedEID")]
    public long ReservedEid { get; set; }
}