// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("runningproduction")]
public partial class Runningproduction
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("characterID")]
    public int CharacterId { get; set; }

    [Column("characterEID")]
    public long CharacterEid { get; set; }

    [Column("resultDefinition")]
    public int ResultDefinition { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("startTime", TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column("finishTime", TypeName = "datetime")]
    public DateTime FinishTime { get; set; }

    [Column("facilityEID")]
    public long FacilityEid { get; set; }

    [Column("totalProductionTime")]
    public int TotalProductionTime { get; set; }

    [Column("baseEID")]
    public long BaseEid { get; set; }

    [Column("creditTaken")]
    public double CreditTaken { get; set; }

    [Column("pricePerSecond")]
    public double PricePerSecond { get; set; }

    [Column("licenseAmount")]
    public int LicenseAmount { get; set; }

    [Column("amountOfCycles")]
    public int AmountOfCycles { get; set; }

    [Column("useCorporationWallet")]
    public bool UseCorporationWallet { get; set; }

    [Column("paused")]
    public bool Paused { get; set; }

    [Column("pausetime", TypeName = "datetime")]
    public DateTime? Pausetime { get; set; }
}