// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("savedeffects")]
public partial class Savedeffect
{
    [Column("eid")]
    public long Eid { get; set; }

    [Required]
    [Column("effects")]
    [Unicode(false)]
    public string Effects { get; set; }
}