// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("siegeitems")]
public partial class Siegeitem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("minquantity")]
    public int Minquantity { get; set; }

    [Column("maxquantity")]
    public int Maxquantity { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Siegeitems")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}