// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("sparks")]
[Index("Sparkname", Name = "IX_sparks", IsUnique = true)]
public partial class Spark
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("sparkname")]
    [StringLength(128)]
    [Unicode(false)]
    public string Sparkname { get; set; }

    [Column("unlockprice")]
    public int? Unlockprice { get; set; }

    [Column("energycredit")]
    public int? Energycredit { get; set; }

    [Column("standinglimit")]
    public double? Standinglimit { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("changeprice")]
    public int Changeprice { get; set; }

    [Column("displayorder")]
    public int Displayorder { get; set; }

    [Column("defaultspark")]
    public bool Defaultspark { get; set; }

    [Column("icon")]
    [StringLength(128)]
    [Unicode(false)]
    public string Icon { get; set; }

    [Column("hidden")]
    public bool Hidden { get; set; }

    [Column("note")]
    [StringLength(1024)]
    public string Note { get; set; }

    [Column("allianceeid")]
    public long? Allianceeid { get; set; }

    [Column("alliancename")]
    [StringLength(128)]
    [Unicode(false)]
    public string Alliancename { get; set; }

    [Column("unlockable")]
    public bool Unlockable { get; set; }

    [InverseProperty("Spark")]
    public virtual ICollection<Sparkextension> Sparkextensions { get; set; } = new List<Sparkextension>();
}