// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("standinglog")]
[Index("Characterid", "Eventtime", Name = "IX_standinglog", IsDescending = new[] { false, true })]
public partial class Standinglog
{
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("actual")]
    public double Actual { get; set; }

    [Column("change")]
    public double Change { get; set; }

    [Column("allianceeid")]
    public long Allianceeid { get; set; }

    [Column("missionid")]
    public int? Missionid { get; set; }
}