// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("steamkeys")]
[Index("Accountid", Name = "IX_steamkeys")]
public partial class Steamkey
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("accountid")]
    public int? Accountid { get; set; }

    [Column("steamid")]
    [StringLength(64)]
    [Unicode(false)]
    public string Steamid { get; set; }

    [Required]
    [Column("steamkey")]
    [StringLength(32)]
    [Unicode(false)]
    public string Steamkey1 { get; set; }

    [Column("assigned", TypeName = "datetime")]
    public DateTime? Assigned { get; set; }
}