// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("steamkeyscomp")]
public partial class Steamkeyscomp
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("steamkey")]
    [StringLength(32)]
    [Unicode(false)]
    public string Steamkey { get; set; }

    [Column("givenaway", TypeName = "date")]
    public DateTime? Givenaway { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }
}