// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("storeitems")]
public partial class Storeitem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("price")]
    public int Price { get; set; }

    [Column("category")]
    public int Category { get; set; }

    [ForeignKey("Category")]
    [InverseProperty("Storeitems")]
    public virtual Storecategory CategoryNavigation { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Storeitems")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}