// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("strongholdexitconfig")]
public partial class Strongholdexitconfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }

    [Column("riftConfigId")]
    public int? RiftConfigId { get; set; }
}