// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("techlineincrement")]
[Index("Definition", "Techlineid", Name = "IX_techlineincrement", IsUnique = true)]
public partial class Techlineincrement
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("techlineid")]
    public int Techlineid { get; set; }

    [Column("multiplier")]
    public double Multiplier { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Techlineincrements")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Techlineid")]
    [InverseProperty("Techlineincrements")]
    public virtual Techline Techline { get; set; }
}