// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("techtreegroups")]
public partial class Techtreegroup
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(64)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("enablerextensionid")]
    public int? Enablerextensionid { get; set; }

    [Column("displayOrder")]
    public int? DisplayOrder { get; set; }
}