// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("techtreepoints")]
[Index("Id", "Owner", "Pointtype", "Amount", Name = "ix_all")]
[Index("Id", Name = "ix_id")]
[Index("Owner", Name = "ix_owner")]
public partial class Techtreepoint
{
    [Column("id")]
    public int Id { get; set; }

    [Column("owner")]
    public long Owner { get; set; }

    [Column("pointtype")]
    public int Pointtype { get; set; }

    [Column("amount")]
    public int Amount { get; set; }
}