// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("techline")]
public partial class Techline
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [InverseProperty("Techline")]
    public virtual ICollection<Techlineincrement> Techlineincrements { get; set; } = new List<Techlineincrement>();

    [InverseProperty("Techline")]
    public virtual ICollection<Techlinemember> Techlinemembers { get; set; } = new List<Techlinemember>();
}