// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("trainingrewards")]
public partial class Trainingreward
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("level")]
    public int Level { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("robottemplateid")]
    public int? Robottemplateid { get; set; }

    [Column("raceid")]
    public int Raceid { get; set; }
}