// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("transportassignmentslog")]
public partial class Transportassignmentslog
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("assignmentevent")]
    public int Assignmentevent { get; set; }

    [Column("baseeid")]
    public long Baseeid { get; set; }

    [Column("ownercharacterid")]
    public int Ownercharacterid { get; set; }

    [Column("volunteercharacterid")]
    public int? Volunteercharacterid { get; set; }

    [Column("assignmentid")]
    public int Assignmentid { get; set; }

    [Required]
    [Column("containername")]
    [StringLength(10)]
    [Unicode(false)]
    public string Containername { get; set; }
}