// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Keyless]
[Table("usercount")]
public partial class Usercount
{
    [Column("time", TypeName = "datetime")]
    public DateTime Time { get; set; }

    [Column("usercount")]
    public int Usercount1 { get; set; }
}