// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("votes")]
public partial class Vote
{
    [Key]
    [Column("voteid")]
    public int Voteid { get; set; }

    [Column("groupEID")]
    public long GroupEid { get; set; }

    [Required]
    [Column("votename")]
    [StringLength(50)]
    public string Votename { get; set; }

    [Column("votetopic")]
    [StringLength(2048)]
    public string Votetopic { get; set; }

    [Column("participation")]
    public int Participation { get; set; }

    [Column("votetype")]
    public int Votetype { get; set; }

    [Column("closed")]
    public bool Closed { get; set; }

    [Column("startdate", TypeName = "smalldatetime")]
    public DateTime Startdate { get; set; }

    [Column("enddate", TypeName = "smalldatetime")]
    public DateTime? Enddate { get; set; }

    [Column("result")]
    public bool? Result { get; set; }

    [Column("startedby")]
    public int Startedby { get; set; }

    [Column("consensusrate")]
    public int Consensusrate { get; set; }
}