// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("yellowpages")]
[Index("CorporationEid", Name = "IX_yellowpages", IsUnique = true)]
public partial class Yellowpage
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("primaryActivity")]
    public int PrimaryActivity { get; set; }

    [Column("zoneID")]
    public int? ZoneId { get; set; }

    [Column("baseEID")]
    public long? BaseEid { get; set; }

    [Column("orientation")]
    public int Orientation { get; set; }

    [Column("lookingFor")]
    public int LookingFor { get; set; }

    [Column("preferredFaction")]
    public int? PreferredFaction { get; set; }

    [Column("providesInsurance")]
    public int ProvidesInsurance { get; set; }

    [Column("timeZone")]
    public int TimeZone { get; set; }

    [Column("requiredActivity")]
    public int RequiredActivity { get; set; }

    [Column("communication")]
    public int Communication { get; set; }

    [Column("services")]
    public int Services { get; set; }
}