// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("zoneeffects")]
public partial class Zoneeffect
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("effectid")]
    public int Effectid { get; set; }
}