// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("zonesectors")]
[Index("Name", Name = "IX_zonesectors_name", IsUnique = true)]
public partial class Zonesector
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Required]
    [Column("sector")]
    [MaxLength(512)]
    public byte[] Sector { get; set; }

    [ForeignKey("Zoneid")]
    [InverseProperty("Zonesectors")]
    public virtual Zone Zone { get; set; }
}