// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Entities;

[Table("zones")]
public partial class Zone
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// description token
    /// </summary>
    [Column("description")]
    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    /// <summary>
    /// developer note
    /// </summary>
    [Column("note")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("fertility")]
    public int Fertility { get; set; }

    [Column("zoneplugin")]
    [StringLength(50)]
    public string Zoneplugin { get; set; }

    [Column("zoneip")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneip { get; set; }

    [Column("zoneport")]
    public int Zoneport { get; set; }

    [Column("isinstance")]
    public bool Isinstance { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [Column("spawnid")]
    public int? Spawnid { get; set; }

    [Column("plantruleset")]
    public int Plantruleset { get; set; }

    [Column("protected")]
    public bool Protected { get; set; }

    [Column("raceid")]
    public int Raceid { get; set; }

    [Column("width")]
    public int Width { get; set; }

    [Column("height")]
    public int Height { get; set; }

    [Column("terraformable")]
    public bool Terraformable { get; set; }

    [Column("zonetype")]
    public int Zonetype { get; set; }

    [Column("sparkcost")]
    public int Sparkcost { get; set; }

    [Column("maxdockingbase")]
    public int Maxdockingbase { get; set; }

    [Column("sleeping")]
    public bool Sleeping { get; set; }

    [Column("plantaltitudescale")]
    public double Plantaltitudescale { get; set; }

    [Column("host")]
    [StringLength(50)]
    [Unicode(false)]
    public string Host { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Column("timeLimitMinutes")]
    public int? TimeLimitMinutes { get; set; }

    [Column("pbsTechLimit")]
    public int? PbsTechLimit { get; set; }

    public int? PlantsGrowthTimerOverrideMin { get; set; }

    [InverseProperty("SourcezoneNavigation")]
    public virtual ICollection<Teleportdescription> TeleportdescriptionSourcezoneNavigations { get; set; } = new List<Teleportdescription>();

    [InverseProperty("TargetzoneNavigation")]
    public virtual ICollection<Teleportdescription> TeleportdescriptionTargetzoneNavigations { get; set; } = new List<Teleportdescription>();

    [InverseProperty("Zone")]
    public virtual ICollection<Zoneentity> Zoneentities { get; set; } = new List<Zoneentity>();

    [InverseProperty("Zone")]
    public virtual ICollection<Zonesector> Zonesectors { get; set; } = new List<Zonesector>();
}