// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("accountcampaignitems")]
[Index("Accountid", "Campaignid", Name = "IX_accountcampaignitems_uk", IsUnique = true)]
public partial class Accountcampaignitem
{
    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("campaignid")]
    public int Campaignid { get; set; }

    [Column("redeemed")]
    public bool Redeemed { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("redeemdate", TypeName = "datetime")]
    public DateTime? Redeemdate { get; set; }
}