// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("accountpremiumpackages")]
[Index("Accountid", "Packageid", Name = "IX_one_pack_per_acc", IsUnique = true)]
public partial class Accountpremiumpackage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("packageid")]
    public int Packageid { get; set; }

    [Column("purchasetime", TypeName = "datetime")]
    public DateTime Purchasetime { get; set; }

    [ForeignKey("Accountid")]
    [InverseProperty("Accountpremiumpackages")]
    public virtual Account Account { get; set; }

    [ForeignKey("Packageid")]
    [InverseProperty("Accountpremiumpackages")]
    public virtual Package Package { get; set; }
}