// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("accounts")]
[Index("Email", "Password", Name = "IX_accounts_emailpasscombo", IsUnique = true)]
[Index("SteamId", Name = "IX_accounts_steamid")]
[Index("Creation", Name = "IX_creation")]
[Index("Email", Name = "UK_accounts", IsUnique = true)]
public partial class Account
{
    [Key]
    [Column("accountID")]
    public int AccountId { get; set; }

    [Column("email")]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("firstName")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("lastName")]
    [StringLength(50)]
    public string LastName { get; set; }

    [Column("born", TypeName = "smalldatetime")]
    public DateTime? Born { get; set; }

    /// <summary>
    /// account state
    /// </summary>
    [Column("state")]
    public int State { get; set; }

    /// <summary>
    /// access level - a combo of access roles - TRIAL by default
    /// </summary>
    [Column("accLevel")]
    public int AccLevel { get; set; }

    [Column("totalMinsOnline")]
    public int TotalMinsOnline { get; set; }

    [Column("lastLoggedIn", TypeName = "smalldatetime")]
    public DateTime? LastLoggedIn { get; set; }

    [Column("creation", TypeName = "smalldatetime")]
    public DateTime? Creation { get; set; }

    [Column("clientType")]
    public byte ClientType { get; set; }

    [Column("isLoggedIn")]
    public bool IsLoggedIn { get; set; }

    [Column("bantime", TypeName = "smalldatetime")]
    public DateTime? Bantime { get; set; }

    /// <summary>
    /// seconds!
    /// </summary>
    [Column("banlength")]
    public int Banlength { get; set; }

    [Column("bannote")]
    [StringLength(512)]
    public string Bannote { get; set; }

    [Column("emailConfirmed")]
    public bool EmailConfirmed { get; set; }

    [Column("firstcharacter", TypeName = "datetime")]
    public DateTime? Firstcharacter { get; set; }

    [Column("note")]
    [StringLength(1024)]
    public string Note { get; set; }

    [Column("steamID")]
    [StringLength(20)]
    [Unicode(false)]
    public string SteamId { get; set; }

    [Column("twitchAuthToken")]
    [StringLength(256)]
    [Unicode(false)]
    public string TwitchAuthToken { get; set; }

    [Column("credit")]
    public int Credit { get; set; }

    [Column("isactive")]
    public bool Isactive { get; set; }

    [Column("resetcount")]
    public int Resetcount { get; set; }

    [Column("wasreset")]
    public bool Wasreset { get; set; }

    [Column("validUntil", TypeName = "smalldatetime")]
    public DateTime? ValidUntil { get; set; }

    [Column("payingcustomer")]
    public bool Payingcustomer { get; set; }

    [Column("campaignid")]
    [StringLength(64)]
    public string Campaignid { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Accountpremiumpackage> Accountpremiumpackages { get; set; } = new List<Accountpremiumpackage>();
}