// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("aggregatemodifiers")]
public partial class Aggregatemodifier
{
    [Column("categoryflag")]
    public long Categoryflag { get; set; }

    [Column("basefield")]
    public int Basefield { get; set; }

    [Column("modifierfield")]
    public int Modifierfield { get; set; }
}