// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("alliancemembers")]
public partial class Alliancemember
{
    [Column("allianceEID")]
    public long AllianceEid { get; set; }

    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [ForeignKey("AllianceEid")]
    public virtual Alliance AllianceE { get; set; }

    [ForeignKey("CorporationEid")]
    public virtual Corporation CorporationE { get; set; }
}