// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("artifacts")]
[Index("Characterid", "Zoneid", Name = "IX_artifactHelper")]
public partial class Artifact
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("artifacttype")]
    public int Artifacttype { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("positionx")]
    public int Positionx { get; set; }

    [Column("positiony")]
    public int Positiony { get; set; }

    [Column("missionguid")]
    public Guid? Missionguid { get; set; }

    [Column("created", TypeName = "datetime")]
    public DateTime? Created { get; set; }
}