// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("artifacttypes")]
[Index("Name", Name = "IX_artifacttypes_unique", IsUnique = true)]
public partial class Artifacttype
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("goalrange")]
    public int Goalrange { get; set; }

    [Column("npcpresenceid")]
    public int? Npcpresenceid { get; set; }

    [Column("persistent")]
    public bool Persistent { get; set; }

    [Column("minimumloot")]
    public int Minimumloot { get; set; }

    [Column("dynamic")]
    public bool Dynamic { get; set; }
}