// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("beams")]
public partial class Beam
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("cycletime")]
    public int Cycletime { get; set; }

    [Column("startdelay")]
    public int Startdelay { get; set; }

    [Column("description")]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("BeamNavigation")]
    public virtual ICollection<Beamassignment> Beamassignments { get; set; } = new List<Beamassignment>();
}