// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("bulletinentries")]
public partial class Bulletinentry
{
    [Column("entryID")]
    public int EntryId { get; set; }

    [Column("bulletinID")]
    public int BulletinId { get; set; }

    [Column("characterID")]
    public int CharacterId { get; set; }

    [Required]
    [Column("entrytext")]
    [StringLength(2000)]
    public string Entrytext { get; set; }

    [Column("entrydate", TypeName = "datetime")]
    public DateTime Entrydate { get; set; }
}