// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("bulletins")]
public partial class Bulletin
{
    [Column("bulletinID")]
    public int BulletinId { get; set; }

    [Column("groupEID")]
    public long GroupEid { get; set; }

    [Required]
    [Column("title")]
    [StringLength(256)]
    public string Title { get; set; }

    [Column("startdate", TypeName = "datetime")]
    public DateTime Startdate { get; set; }

    [Column("startedby")]
    public int Startedby { get; set; }
}