// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("calibrationdefaults")]
public partial class Calibrationdefault
{
    [Key]
    [Column("definition")]
    public int Definition { get; set; }

    [Column("materialefficiency")]
    public double Materialefficiency { get; set; }

    [Column("timeefficiency")]
    public double Timeefficiency { get; set; }
}