// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("campaigns")]
public partial class Campaign
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("campaigntoken")]
    [StringLength(128)]
    [Unicode(false)]
    public string Campaigntoken { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [InverseProperty("Campaign")]
    public virtual ICollection<Campaigngoodiepack> Campaigngoodiepacks { get; set; } = new List<Campaigngoodiepack>();
}