// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("campaigngoodiepacks")]
[Index("Name", Name = "IX_campaigngoodiepacks", IsUnique = true)]
public partial class Campaigngoodiepack
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(512)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(512)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("campaignid")]
    public int Campaignid { get; set; }

    [Column("credit")]
    public int? Credit { get; set; }

    [Column("ep")]
    public int? Ep { get; set; }

    [Column("faction")]
    [StringLength(8)]
    [Unicode(false)]
    public string Faction { get; set; }

    [Column("item0")]
    public int? Item0 { get; set; }

    [Column("quantity0")]
    public int? Quantity0 { get; set; }

    [Column("item1")]
    public int? Item1 { get; set; }

    [Column("quantity1")]
    public int? Quantity1 { get; set; }

    [Column("item2")]
    public int? Item2 { get; set; }

    [Column("quantity2")]
    public int? Quantity2 { get; set; }

    [Column("item3")]
    public int? Item3 { get; set; }

    [Column("quantity3")]
    public int? Quantity3 { get; set; }

    [Column("item4")]
    public int? Item4 { get; set; }

    [Column("quantity4")]
    public int? Quantity4 { get; set; }

    [Column("item5")]
    public int? Item5 { get; set; }

    [Column("quantity5")]
    public int? Quantity5 { get; set; }

    [Column("item6")]
    public int? Item6 { get; set; }

    [Column("quantity6")]
    public int? Quantity6 { get; set; }

    [Column("item7")]
    public int? Item7 { get; set; }

    [Column("quantity7")]
    public int? Quantity7 { get; set; }

    [Column("item8")]
    public int? Item8 { get; set; }

    [Column("quantity8")]
    public int? Quantity8 { get; set; }

    [Column("item9")]
    public int? Item9 { get; set; }

    [Column("quantity9")]
    public int? Quantity9 { get; set; }

    [ForeignKey("Campaignid")]
    [InverseProperty("Campaigngoodiepacks")]
    public virtual Campaign Campaign { get; set; }
}