// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("categorygroups")]
public partial class Categorygroup
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("groupId")]
    public int GroupId { get; set; }

    [Column("category")]
    public long Category { get; set; }
}