// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("channelbans")]
public partial class Channelban
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("memberid")]
    public int Memberid { get; set; }

    [Column("channelid")]
    public int Channelid { get; set; }
}