// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("channelmembers")]
[Index("Memberid", Name = "IX_channelmembers_memberid")]
[Index("Channelid", "Memberid", Name = "IX_channelmembers_unique", IsUnique = true)]
public partial class Channelmember
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("channelid")]
    public int Channelid { get; set; }

    [Column("memberid")]
    public int Memberid { get; set; }

    [Column("role")]
    public int Role { get; set; }
}