// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("characternotes")]
public partial class Characternote
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("targetid")]
    public int Targetid { get; set; }

    [Required]
    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }
}