// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("combatlog")]
public partial class Combatlog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("date", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("zoneId")]
    public int ZoneId { get; set; }

    [Column("characterId")]
    public int CharacterId { get; set; }

    [Required]
    [Column("data")]
    [Unicode(false)]
    public string Data { get; set; }
}