// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("containerlog")]
public partial class Containerlog
{
    [Column("containerEID")]
    public long ContainerEid { get; set; }

    [Column("memberID")]
    public int MemberId { get; set; }

    [Column("containeraccess")]
    public int Containeraccess { get; set; }

    [Column("operationdate", TypeName = "datetime")]
    public DateTime Operationdate { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }
}