// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("corporationtransactions")]
public partial class Corporationtransaction
{
    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("memberID")]
    public int? MemberId { get; set; }

    [Column("transactiontype")]
    public int Transactiontype { get; set; }

    [Column("amount")]
    public double Amount { get; set; }

    [Column("transactiondate", TypeName = "datetime")]
    public DateTime Transactiondate { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("targetMemberID")]
    public int? TargetMemberId { get; set; }

    [Column("currentwallet")]
    public double Currentwallet { get; set; }

    [Column("involvedCorporationEID")]
    public long? InvolvedCorporationEid { get; set; }
}