// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("corporationdocumentconfig")]
public partial class Corporationdocumentconfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("documenttype")]
    public int Documenttype { get; set; }

    [Column("creationprice")]
    public int Creationprice { get; set; }

    [Column("rentprice")]
    public int Rentprice { get; set; }

    [Column("rentperioddays")]
    public int Rentperioddays { get; set; }

    [Column("maxpercharacter")]
    public int Maxpercharacter { get; set; }

    [Column("note")]
    [StringLength(2048)]
    [Unicode(false)]
    public string Note { get; set; }
}