// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("corporationhistory")]
public partial class Corporationhistory
{
    [Column("characterID")]
    public int CharacterId { get; set; }

    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("corporationJoined", TypeName = "smalldatetime")]
    public DateTime CorporationJoined { get; set; }

    [Column("corporationLeft", TypeName = "smalldatetime")]
    public DateTime? CorporationLeft { get; set; }

    [Key]
    [Column("id")]
    public int Id { get; set; }

    [ForeignKey("CorporationEid")]
    [InverseProperty("Corporationhistories")]
    public virtual Corporation CorporationE { get; set; }
}