// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("corporationrolehistory")]
public partial class Corporationrolehistory
{
    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("issuerID")]
    public int IssuerId { get; set; }

    [Column("memberID")]
    public int MemberId { get; set; }

    [Column("oldrole")]
    public int Oldrole { get; set; }

    [Column("newrole")]
    public int Newrole { get; set; }

    [Column("rolesettime", TypeName = "datetime")]
    public DateTime Rolesettime { get; set; }

    [ForeignKey("CorporationEid")]
    public virtual Corporation CorporationE { get; set; }
}