// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("corporationmembers")]
[Index("CorporationEid", Name = "IX_corpmembers_eidtodata")]
public partial class Corporationmember
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("memberid")]
    public int Memberid { get; set; }

    [Column("role")]
    public int Role { get; set; }

    [ForeignKey("CorporationEid")]
    [InverseProperty("Corporationmembers")]
    public virtual Corporation CorporationE { get; set; }
}