// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("corporationnamehistory")]
public partial class Corporationnamehistory
{
    [Column("corporationeid")]
    public long Corporationeid { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("nick")]
    [StringLength(6)]
    [Unicode(false)]
    public string Nick { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("characterid")]
    public int? Characterid { get; set; }
}