// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("countries")]
[Index("Id", Name = "IX_countries", IsUnique = true)]
public partial class Country
{
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("country")]
    [StringLength(50)]
    [Unicode(false)]
    public string Country1 { get; set; }

    [Column("nick")]
    [StringLength(8)]
    [Unicode(false)]
    public string Nick { get; set; }
}