// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("cw_corporation_extension")]
[Index("CorporationEid", "Extensionid", Name = "IX_cw_corporation_extension", IsUnique = true)]
public partial class CwCorporationExtension
{
    [Key]
    [Column("corporation_extension_id")]
    public int CorporationExtensionId { get; set; }

    [Column("corporationEID")]
    public long CorporationEid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("levelincrement")]
    public int Levelincrement { get; set; }

    [ForeignKey("CorporationEid")]
    [InverseProperty("CwCorporationExtensions")]
    public virtual CwCorporation CorporationE { get; set; }

    [ForeignKey("Extensionid")]
    [InverseProperty("CwCorporationExtensions")]
    public virtual Extension Extension { get; set; }
}