// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("cw_major_extension")]
[Index("Majorid", "Extensionid", Name = "IX_cw_major_extension", IsUnique = true)]
public partial class CwMajorExtension
{
    [Column("major_extension_id")]
    public int MajorExtensionId { get; set; }

    [Column("majorid")]
    public int Majorid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("levelincrement")]
    public int Levelincrement { get; set; }

    [ForeignKey("Extensionid")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Majorid")]
    public virtual CwMajor Major { get; set; }
}