// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("cw_race_extension")]
[Index("Raceid", "Extensionid", Name = "IX_cw_race_extension", IsUnique = true)]
public partial class CwRaceExtension
{
    [Column("race_extension_id")]
    public int RaceExtensionId { get; set; }

    [Column("raceid")]
    public int Raceid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("levelincrement")]
    public int Levelincrement { get; set; }

    [ForeignKey("Extensionid")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Raceid")]
    public virtual CwRace Race { get; set; }
}