// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("cw_school_extension")]
[Index("Schoolid", "Extensionid", Name = "IX_cw_school_extension", IsUnique = true)]
public partial class CwSchoolExtension
{
    [Column("school_extension_id")]
    public int SchoolExtensionId { get; set; }

    [Column("schoolid")]
    public int Schoolid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("levelincrement")]
    public int Levelincrement { get; set; }

    [ForeignKey("Extensionid")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Schoolid")]
    public virtual CwSchool School { get; set; }
}