// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("cw_spark")]
public partial class CwSpark
{
    [Key]
    [Column("sparkid")]
    public int Sparkid { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("attributeA")]
    public double AttributeA { get; set; }

    [Column("attributeB")]
    public double AttributeB { get; set; }

    [Column("attributeC")]
    public double AttributeC { get; set; }

    [Column("attributeD")]
    public double AttributeD { get; set; }

    [Column("attributeE")]
    public double AttributeE { get; set; }

    [Column("attributeF")]
    public double AttributeF { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [Column("descriptiontoken")]
    [StringLength(50)]
    [Unicode(false)]
    public string Descriptiontoken { get; set; }
}