// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("decor")]
public partial class Decor
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quaternionx")]
    public double Quaternionx { get; set; }

    [Column("quaterniony")]
    public double Quaterniony { get; set; }

    [Column("quaternionz")]
    public double Quaternionz { get; set; }

    [Column("quaternionw")]
    public double Quaternionw { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }

    [Column("z")]
    public int Z { get; set; }

    [Column("scale")]
    public double Scale { get; set; }

    [Column("changed")]
    public bool Changed { get; set; }

    [Column("fadedistance")]
    public double Fadedistance { get; set; }

    [Column("category")]
    public int Category { get; set; }

    [Column("locked")]
    public bool Locked { get; set; }

    [ForeignKey("Category")]
    [InverseProperty("Decors")]
    public virtual Decorcategory CategoryNavigation { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Decors")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}