// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("definitionconfig")]
[Index("Definition", Name = "IX_definitionconfig", IsUnique = true)]
public partial class Definitionconfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("targetdefinition")]
    public int? Targetdefinition { get; set; }

    [Column("summonerscount")]
    public int? Summonerscount { get; set; }

    [Column("npcpresenceid")]
    public int? Npcpresenceid { get; set; }

    [Column("item_work_range")]
    public double? ItemWorkRange { get; set; }

    [Column("explosion_radius")]
    public double? ExplosionRadius { get; set; }

    [Column("cycle_time")]
    public int? CycleTime { get; set; }

    [Column("damage_chemical")]
    public double? DamageChemical { get; set; }

    [Column("damage_explosive")]
    public double? DamageExplosive { get; set; }

    [Column("damage_kinetic")]
    public double? DamageKinetic { get; set; }

    [Column("damage_thermal")]
    public double? DamageThermal { get; set; }

    [Column("lifetime")]
    public int? Lifetime { get; set; }

    [Column("activationtime")]
    public int? Activationtime { get; set; }

    [Column("waves")]
    public int? Waves { get; set; }

    [Column("missionrelated")]
    public bool? Missionrelated { get; set; }

    [Column("constructionradius")]
    public int? Constructionradius { get; set; }

    [Column("action_delay")]
    public int? ActionDelay { get; set; }

    [Column("deploy_radius")]
    public int? DeployRadius { get; set; }

    [Column("transmitradius")]
    public int? Transmitradius { get; set; }

    [Column("constructionlevelmax")]
    public int? Constructionlevelmax { get; set; }

    [Column("blockingradius")]
    public int? Blockingradius { get; set; }

    [Column("chargeamount")]
    public int? Chargeamount { get; set; }

    [Column("inconnections")]
    public int? Inconnections { get; set; }

    [Column("outconnections")]
    public int? Outconnections { get; set; }

    [Column("coretransferred")]
    public double? Coretransferred { get; set; }

    [Column("transferefficiency")]
    public double? Transferefficiency { get; set; }

    [Column("productionupgradeamount")]
    public int? Productionupgradeamount { get; set; }

    [Column("productionlevel")]
    public int? Productionlevel { get; set; }

    [Column("coreconsumption")]
    public double? Coreconsumption { get; set; }

    [Column("effectid")]
    public int? Effectid { get; set; }

    [Column("corecalories")]
    public double? Corecalories { get; set; }

    [Column("corekickstartthreshold")]
    public double? Corekickstartthreshold { get; set; }

    [Column("reinforcecountermax")]
    public int? Reinforcecountermax { get; set; }

    [Column("bandwidthusage")]
    public int? Bandwidthusage { get; set; }

    [Column("bandwidthcapacity")]
    public int? Bandwidthcapacity { get; set; }

    [Column("emitradius")]
    public int? Emitradius { get; set; }

    [Column("tint")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tint { get; set; }

    [Column("typeexclusiverange")]
    public int? Typeexclusiverange { get; set; }

    [Column("network_node_range")]
    public int? NetworkNodeRange { get; set; }

    [Column("hitsize")]
    public double? Hitsize { get; set; }

    [Column("note")]
    [StringLength(2000)]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("damage_toxic")]
    public double? DamageToxic { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Definitionconfig")]
    public virtual Entitydefault DefinitionNavigation { get; set; }
}