// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("effectdefaultmodifiers")]
public partial class Effectdefaultmodifier
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("effectid")]
    public int Effectid { get; set; }

    [Column("field")]
    public int Field { get; set; }

    [Column("value")]
    public double Value { get; set; }

    [ForeignKey("Field")]
    [InverseProperty("Effectdefaultmodifiers")]
    public virtual Aggregatefield FieldNavigation { get; set; }
}