// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("enablerextensions")]
[Index("Definition", Name = "IX_enablerextensions")]
public partial class Enablerextension
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("extensionlevel")]
    public int Extensionlevel { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Enablerextensions")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Extensionid")]
    [InverseProperty("Enablerextensions")]
    public virtual Extension Extension { get; set; }
}