// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("entitytrash")]
[Index("Wasinsured", Name = "IX_trashHelper")]
public partial class Entitytrash
{
    [Column("eid")]
    public long Eid { get; set; }

    [Column("deleted", TypeName = "datetime")]
    public DateTime Deleted { get; set; }

    [Column("wasinsured")]
    public bool Wasinsured { get; set; }

    [Column("killedbyplayer")]
    public bool Killedbyplayer { get; set; }

    [Column("inactiveperiod")]
    public int Inactiveperiod { get; set; }

    [Column("dctime", TypeName = "datetime")]
    public DateTime? Dctime { get; set; }
}