// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("extensioncategories")]
public partial class Extensioncategory
{
    [Key]
    [Column("extensioncategoryid")]
    public int Extensioncategoryid { get; set; }

    [Required]
    [Column("categoryname")]
    [StringLength(50)]
    [Unicode(false)]
    public string Categoryname { get; set; }

    [Column("hidden")]
    public bool Hidden { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }

    [InverseProperty("CategoryNavigation")]
    public virtual ICollection<Extension> Extensions { get; set; } = new List<Extension>();
}