// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("extensionprerequire")]
public partial class Extensionprerequire
{
    [Column("extensionprerequireid")]
    public int Extensionprerequireid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("requiredextension")]
    public int Requiredextension { get; set; }

    [Column("requiredlevel")]
    public int Requiredlevel { get; set; }

    [ForeignKey("Extensionid")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Requiredextension")]
    public virtual Extension RequiredextensionNavigation { get; set; }
}