// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("extensionremovelog")]
public partial class Extensionremovelog
{
    [Column("id")]
    public int Id { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("extensionlevel")]
    public int Extensionlevel { get; set; }

    [Column("points")]
    public int Points { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }
}