// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("facilitymap")]
public partial class Facilitymap
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Required]
    [Column("defname")]
    [StringLength(50)]
    [Unicode(false)]
    public string Defname { get; set; }

    [Column("leveltag")]
    [StringLength(50)]
    public string Leveltag { get; set; }
}