// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("gameglobals")]
public partial class Gameglobal
{
    [Column("clockoffset")]
    public long Clockoffset { get; set; }

    [Column("active", TypeName = "smalldatetime")]
    public DateTime? Active { get; set; }

    [Column("bankcredit")]
    public long Bankcredit { get; set; }

    [Column("lastonline", TypeName = "datetime")]
    public DateTime? Lastonline { get; set; }
}