// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("hardwareinfo")]
public partial class Hardwareinfo
{
    [Key]
    [Column("accountid")]
    public int Accountid { get; set; }

    [Required]
    [Column("gfxcard")]
    [StringLength(128)]
    [Unicode(false)]
    public string Gfxcard { get; set; }

    [Column("gfxdriver")]
    [StringLength(128)]
    [Unicode(false)]
    public string Gfxdriver { get; set; }

    [Column("gfxvendorid")]
    public int Gfxvendorid { get; set; }

    [Column("gfxdeviceid")]
    public int Gfxdeviceid { get; set; }

    [Column("gfxdriverversion")]
    public long Gfxdriverversion { get; set; }

    [Column("pixelshader")]
    public long Pixelshader { get; set; }

    [Column("vertexshader")]
    public long Vertexshader { get; set; }

    [Column("maxtexturex")]
    public int Maxtexturex { get; set; }

    [Column("maxtexturey")]
    public int Maxtexturey { get; set; }

    [Column("osversion")]
    [StringLength(128)]
    [Unicode(false)]
    public string Osversion { get; set; }
}