// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("icetracker")]
public partial class Icetracker
{
    [Column("eid")]
    public long Eid { get; set; }

    [Column("usedbytrial")]
    public bool Usedbytrial { get; set; }

    [Column("usedat", TypeName = "datetime")]
    public DateTime Usedat { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }
}