// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("insurance")]
public partial class Insurance
{
    [Column("eid")]
    public long Eid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("corporationeid")]
    public long? Corporationeid { get; set; }

    [Column("insurancetype")]
    public int Insurancetype { get; set; }

    [Column("enddate", TypeName = "datetime")]
    public DateTime Enddate { get; set; }

    [Column("payout")]
    public double Payout { get; set; }
}