// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("intrusionproductionstack")]
public partial class Intrusionproductionstack
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("facilityeid")]
    public long Facilityeid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }
}