// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("intrusioneffectlog")]
public partial class Intrusioneffectlog
{
    [Column("characterid")]
    public int? Characterid { get; set; }

    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("effectid")]
    public int? Effectid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }

    [Column("eventtype")]
    public int Eventtype { get; set; }
}