// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("intrusionsapdeploylog")]
public partial class Intrusionsapdeploylog
{
    [Column("deploytime", TypeName = "datetime")]
    public DateTime Deploytime { get; set; }

    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("sapdefinition")]
    public int Sapdefinition { get; set; }
}