// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("intrusionsaps")]
public partial class Intrusionsap
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }
}