// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("intrusionsitestabilitythreshold")]
public partial class Intrusionsitestabilitythreshold
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("categoryflag")]
    public long Categoryflag { get; set; }

    [Column("threshold")]
    public int Threshold { get; set; }

    [Column("bonustype")]
    public int Bonustype { get; set; }

    [Column("effecttype")]
    public int? Effecttype { get; set; }
}