// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("intrusionsitelog")]
public partial class Intrusionsitelog
{
    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }

    [Column("stability")]
    public int Stability { get; set; }

    [Column("winnercorporationeid")]
    public long? Winnercorporationeid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("sapdefinition")]
    public int Sapdefinition { get; set; }

    [Column("oldstability")]
    public int Oldstability { get; set; }

    [Column("oldowner")]
    public long? Oldowner { get; set; }

    [Column("eventtype")]
    public int Eventtype { get; set; }
}