// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("intrusionproductionlog")]
public partial class Intrusionproductionlog
{
    [Column("siteeid")]
    public long Siteeid { get; set; }

    [Column("eventtype")]
    public int Eventtype { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("facilitydefinition")]
    public int? Facilitydefinition { get; set; }

    [Column("facilitylevel")]
    public int? Facilitylevel { get; set; }

    [Column("oldfacilitylevel")]
    public int? Oldfacilitylevel { get; set; }

    [Column("characterid")]
    public int? Characterid { get; set; }

    [Column("points")]
    public int? Points { get; set; }

    [Column("oldpoints")]
    public int? Oldpoints { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }
}