// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("itemshop")]
public partial class Itemshop
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("presetid")]
    public int Presetid { get; set; }

    [Column("targetdefinition")]
    public int Targetdefinition { get; set; }

    [Column("targetamount")]
    public int Targetamount { get; set; }

    [Column("tmcoin")]
    public int? Tmcoin { get; set; }

    [Column("icscoin")]
    public int? Icscoin { get; set; }

    [Column("asicoin")]
    public int? Asicoin { get; set; }

    [Column("credit")]
    public double? Credit { get; set; }

    [Column("unicoin")]
    public int? Unicoin { get; set; }

    [Column("globallimit")]
    public int? Globallimit { get; set; }

    [Column("purchasecount")]
    public int Purchasecount { get; set; }

    [Column("standing")]
    public double? Standing { get; set; }

    [ForeignKey("Targetdefinition")]
    [InverseProperty("Itemshops")]
    public virtual Entitydefault TargetdefinitionNavigation { get; set; }
}