// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("itemshoplocations")]
[Index("Locationeid", "Presetid", Name = "IX_itemshoplocations", IsUnique = true)]
public partial class Itemshoplocation
{
    [Key]
    [Column("locationeid")]
    public long Locationeid { get; set; }

    [Column("presetid")]
    public int Presetid { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [ForeignKey("Presetid")]
    [InverseProperty("Itemshoplocations")]
    public virtual Itemshoppreset Preset { get; set; }
}