// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("itemcreation")]
public partial class Itemcreation
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    public int Entity { get; set; }

    public int Qty { get; set; }

    public int CharacterId { get; set; }

    public int IsTraining { get; set; }

    public int ZoneId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateTime { get; set; }
}