// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("itemshoppresets")]
public partial class Itemshoppreset
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [InverseProperty("Preset")]
    public virtual ICollection<Itemshoplocation> Itemshoplocations { get; set; } = new List<Itemshoplocation>();
}