// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("lootitems")]
public partial class Lootitem
{
    [Column("id")]
    public Guid? Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("health")]
    public double Health { get; set; }

    [Column("repackaged")]
    public bool Repackaged { get; set; }

    [Column("containereid")]
    public long Containereid { get; set; }
}