// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("lotteryitemweights")]
public partial class Lotteryitemweight
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("lotterydefinition")]
    public int Lotterydefinition { get; set; }

    [Column("categoryflags")]
    public long Categoryflags { get; set; }

    [Column("tiertype")]
    public int Tiertype { get; set; }

    [Column("tierlevel")]
    public int Tierlevel { get; set; }

    [Column("weight")]
    public double Weight { get; set; }
}