// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("markettaxlog")]
public partial class Markettaxlog
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("owner")]
    public long Owner { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("baseeid")]
    public long Baseeid { get; set; }

    [Column("changefrom")]
    public double Changefrom { get; set; }

    [Column("changeto")]
    public double Changeto { get; set; }
}