// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("marketitems")]
public partial class Marketitem
{
    [Key]
    [Column("marketitemid")]
    public int Marketitemid { get; set; }

    [Column("marketeid")]
    public long Marketeid { get; set; }

    [Column("itemeid")]
    public long? Itemeid { get; set; }

    [Column("itemdefinition")]
    public int Itemdefinition { get; set; }

    [Column("submittereid")]
    public long Submittereid { get; set; }

    [Column("submitted", TypeName = "smalldatetime")]
    public DateTime Submitted { get; set; }

    /// <summary>
    /// in hours
    /// </summary>
    [Column("duration")]
    public int Duration { get; set; }

    [Column("isSell")]
    public bool IsSell { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("usecorporationwallet")]
    public bool Usecorporationwallet { get; set; }

    [Column("isvendoritem")]
    public bool Isvendoritem { get; set; }

    [Column("formembersof")]
    public long? Formembersof { get; set; }
}