// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("mineralconfigs")]
[Index("Zoneid", "Materialtype", Name = "IX_mineralconfigs", IsUnique = true)]
public partial class Mineralconfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("materialtype")]
    public int Materialtype { get; set; }

    [Column("maxnodes")]
    public int Maxnodes { get; set; }

    [Column("maxtilespernode")]
    public int Maxtilespernode { get; set; }

    [Column("totalamountpernode")]
    public int Totalamountpernode { get; set; }

    [Column("minthreshold")]
    public double Minthreshold { get; set; }
}