// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("minerals")]
public partial class Mineral
{
    [Column("idx")]
    public int Idx { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("amount")]
    public int Amount { get; set; }

    [Column("extractionType")]
    public int ExtractionType { get; set; }

    [Column("enablereffectrequired")]
    public bool Enablereffectrequired { get; set; }

    [Column("note")]
    [StringLength(1024)]
    public string Note { get; set; }

    [Column("geoscandocument")]
    public int? Geoscandocument { get; set; }
}