// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("mineralscan")]
[Index("Ownerid", Name = "IX_1")]
public partial class Mineralscan
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("ownerid")]
    public int Ownerid { get; set; }

    [Column("materialprobetype")]
    public byte Materialprobetype { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("materialtype")]
    public byte Materialtype { get; set; }

    [Column("x1")]
    public int X1 { get; set; }

    [Column("y1")]
    public int Y1 { get; set; }

    [Column("x2")]
    public int X2 { get; set; }

    [Column("y2")]
    public int Y2 { get; set; }

    [Column("scanAccuracy")]
    public double ScanAccuracy { get; set; }

    [Column("folder")]
    [StringLength(32)]
    public string Folder { get; set; }

    [Column("quality")]
    public long Quality { get; set; }
}