// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("mininglog")]
public partial class Mininglog
{
    [Column("eventtime", TypeName = "smalldatetime")]
    public DateTime Eventtime { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("amount")]
    public int Amount { get; set; }
}