// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionpayoutlog")]
public partial class Missionpayoutlog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("missionguid")]
    public Guid Missionguid { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [Column("missioncategory")]
    public int Missioncategory { get; set; }

    [Column("missionlevel")]
    public int Missionlevel { get; set; }

    [Column("corporationeid")]
    public long? Corporationeid { get; set; }

    [Column("characterid")]
    public int? Characterid { get; set; }

    [Column("gangsize")]
    public int Gangsize { get; set; }

    [Column("amount")]
    public double Amount { get; set; }

    [Column("sumamount")]
    public double Sumamount { get; set; }
}