// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionstartitem")]
public partial class Missionstartitem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Missionstartitems")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Missionid")]
    [InverseProperty("Missionstartitems")]
    public virtual Mission Mission { get; set; }
}