// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionlog")]
[Index("MissionGuid", Name = "IX_missionlog_guid", IsUnique = true)]
[Index("Finished", Name = "missionlog_ixx")]
public partial class Missionlog
{
    [Key]
    [Column("missionGuid")]
    public Guid MissionGuid { get; set; }

    [Column("missionID")]
    public int MissionId { get; set; }

    [Column("characterID")]
    public int CharacterId { get; set; }

    [Column("started", TypeName = "datetime")]
    public DateTime Started { get; set; }

    [Column("finished", TypeName = "datetime")]
    public DateTime? Finished { get; set; }

    [Column("succeeded")]
    public bool Succeeded { get; set; }

    [Column("expire", TypeName = "datetime")]
    public DateTime? Expire { get; set; }

    [Column("grouporder")]
    public int Grouporder { get; set; }

    [Column("spreadingang")]
    public bool Spreadingang { get; set; }

    [Column("bonusmultiplier")]
    public double Bonusmultiplier { get; set; }

    [Column("locationid")]
    public int? Locationid { get; set; }

    [Column("missionlevel")]
    public int? Missionlevel { get; set; }

    [Column("issuercorporationeid")]
    public long? Issuercorporationeid { get; set; }

    [Column("issuerallianceeid")]
    public long? Issuerallianceeid { get; set; }

    [Column("selectedrace")]
    public int? Selectedrace { get; set; }

    [Column("rewarddivider")]
    public int Rewarddivider { get; set; }
}