// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionrequiredextensions")]
public partial class Missionrequiredextension
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("extensionlevel")]
    public int Extensionlevel { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [ForeignKey("Extensionid")]
    [InverseProperty("Missionrequiredextensions")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Missionid")]
    [InverseProperty("Missionrequiredextensions")]
    public virtual Mission Mission { get; set; }
}