// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missiontargets")]
public partial class Missiontarget
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(512)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(128)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("missionid")]
    public int? Missionid { get; set; }

    [Column("targettype")]
    public int Targettype { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("targetpositionx")]
    public int? Targetpositionx { get; set; }

    [Column("targetpositiony")]
    public int? Targetpositiony { get; set; }

    [Column("targetpositionrange")]
    public int? Targetpositionrange { get; set; }

    [Column("targetpositionzone")]
    public int? Targetpositionzone { get; set; }

    [Column("scantype")]
    public int? Scantype { get; set; }

    [Column("checkposition")]
    public bool Checkposition { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("completedmessage")]
    [StringLength(128)]
    [Unicode(false)]
    public string Completedmessage { get; set; }

    [Column("activatedmessage")]
    [StringLength(128)]
    [Unicode(false)]
    public string Activatedmessage { get; set; }

    [Column("artifacttype")]
    public int? Artifacttype { get; set; }

    [Column("teleportchannel")]
    public int? Teleportchannel { get; set; }

    [Column("npcpresenceid")]
    public int? Npcpresenceid { get; set; }

    [Column("targetorder")]
    public int Targetorder { get; set; }

    [Column("displayorder")]
    public int Displayorder { get; set; }

    [Column("branchmissionid")]
    public int? Branchmissionid { get; set; }

    [Column("optional")]
    public bool Optional { get; set; }

    [Column("hidden")]
    public bool Hidden { get; set; }

    [Column("structureeid")]
    public long? Structureeid { get; set; }

    [Column("primarydefinitionfromindex")]
    public int? Primarydefinitionfromindex { get; set; }

    [Column("secondarydefinitionfromindex")]
    public int? Secondarydefinitionfromindex { get; set; }

    [Column("findradius")]
    public int? Findradius { get; set; }

    [Column("spawnnpcs")]
    public bool Spawnnpcs { get; set; }

    [Column("snaptonextstructure")]
    public bool Snaptonextstructure { get; set; }

    [Column("generatesecondarydefinition")]
    public bool Generatesecondarydefinition { get; set; }

    [Column("targetsecondaryasmyprimary")]
    public bool Targetsecondaryasmyprimary { get; set; }

    [Column("targetprimaryasmysecondary")]
    public bool Targetprimaryasmysecondary { get; set; }

    [Column("anylocation")]
    public bool Anylocation { get; set; }

    [Column("usequantityonly")]
    public bool Usequantityonly { get; set; }

    [Column("generateresearchkit")]
    public bool Generateresearchkit { get; set; }

    [Column("generatecprg")]
    public bool Generatecprg { get; set; }

    [Column("primarycategory")]
    public long? Primarycategory { get; set; }

    [Column("secondarycategory")]
    public long? Secondarycategory { get; set; }

    [Column("secondaryquantity")]
    public int? Secondaryquantity { get; set; }

    [Column("scaleprimaryqwithlevel")]
    public bool Scaleprimaryqwithlevel { get; set; }

    [Column("scalesecondaryqwithlevel")]
    public bool Scalesecondaryqwithlevel { get; set; }

    [Column("primaryscalemult")]
    public double? Primaryscalemult { get; set; }

    [Column("secondaryscalemult")]
    public double? Secondaryscalemult { get; set; }

    [Column("structurename")]
    [StringLength(128)]
    public string Structurename { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Missiontargets")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Targettype")]
    [InverseProperty("Missiontargets")]
    public virtual Missiontargettype TargettypeNavigation { get; set; }
}