// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missiontargettypes")]
public partial class Missiontargettype
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("reward")]
    public int Reward { get; set; }

    [InverseProperty("TargettypeNavigation")]
    public virtual ICollection<Missiontarget> Missiontargets { get; set; } = new List<Missiontarget>();
}