// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missiontolocation")]
public partial class Missiontolocation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [Column("locationid")]
    public int Locationid { get; set; }

    [Column("attempts")]
    public int Attempts { get; set; }

    [Column("success")]
    public int Success { get; set; }

    [Column("uniquecases")]
    public int Uniquecases { get; set; }

    [Column("rewardaverage")]
    public int? Rewardaverage { get; set; }
}