// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missiontoagent")]
[Index("Missionid", "Agentid", Name = "IX_missiontoagent_unique", IsUnique = true)]
public partial class Missiontoagent
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [Column("agentid")]
    public int Agentid { get; set; }
}