// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionrewards")]
public partial class Missionreward
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("probability")]
    public int Probability { get; set; }

    [Column("missionid")]
    public int Missionid { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Missionrewards")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Missionid")]
    [InverseProperty("Missionrewards")]
    public virtual Mission Mission { get; set; }
}