// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionrequiredmissions")]
[Index("Mission", "Requiredmission", Name = "IX_missionrequiredmissions_unique", IsUnique = true)]
public partial class Missionrequiredmission
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("mission")]
    public int Mission { get; set; }

    [Column("requiredmission")]
    public int Requiredmission { get; set; }

    [ForeignKey("Mission")]
    [InverseProperty("MissionrequiredmissionMissionNavigations")]
    public virtual Mission MissionNavigation { get; set; }

    [ForeignKey("Requiredmission")]
    [InverseProperty("MissionrequiredmissionRequiredmissionNavigations")]
    public virtual Mission RequiredmissionNavigation { get; set; }
}