// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionlocations")]
[Index("Locationeid", Name = "IX_missionlocations_locationeid_unique", IsUnique = true)]
[Index("Agentid", "Locationeid", Name = "IX_missionlocations_unique", IsUnique = true)]
public partial class Missionlocation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("agentid")]
    public int Agentid { get; set; }

    [Column("locationeid")]
    public long Locationeid { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public double X { get; set; }

    [Column("y")]
    public double Y { get; set; }

    [Column("maxmissionlevel")]
    public int Maxmissionlevel { get; set; }

    [Column("locationname")]
    [StringLength(128)]
    public string Locationname { get; set; }

    [Column("dontsync")]
    public bool Dontsync { get; set; }
}