// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionagents")]
public partial class Missionagent
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("agentname")]
    [StringLength(128)]
    [Unicode(false)]
    public string Agentname { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }

    [Column("ownername")]
    [StringLength(128)]
    [Unicode(false)]
    public string Ownername { get; set; }

    [InverseProperty("SourceagentNavigation")]
    public virtual ICollection<Mission> Missions { get; set; } = new List<Mission>();
}