// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missionparticipants")]
[Index("Missionguid", "Characterid", Name = "IX_missionparticipants")]
public partial class Missionparticipant
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("missionguid")]
    public Guid Missionguid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }
}