// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("missions")]
public partial class Mission
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("title")]
    [StringLength(128)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    [Column("description")]
    [StringLength(128)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("missiontype")]
    public int Missiontype { get; set; }

    [Column("issuerid")]
    public int? Issuerid { get; set; }

    [Column("missionidonfail")]
    public int? Missionidonfail { get; set; }

    [Column("missionidonsuccess")]
    public int? Missionidonsuccess { get; set; }

    [Column("isunique")]
    public bool Isunique { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("missionpack")]
    public int Missionpack { get; set; }

    [Column("periodminutes")]
    public int? Periodminutes { get; set; }

    [Column("missionlevel")]
    public int? Missionlevel { get; set; }

    [Column("durationminutes")]
    public int Durationminutes { get; set; }

    [Column("successmessage")]
    [StringLength(128)]
    [Unicode(false)]
    public string Successmessage { get; set; }

    [Column("failmessage")]
    [StringLength(128)]
    [Unicode(false)]
    public string Failmessage { get; set; }

    [Column("listable")]
    public bool Listable { get; set; }

    [Column("alwaysenabled")]
    public bool Alwaysenabled { get; set; }

    [Column("rewardfee")]
    public double Rewardfee { get; set; }

    [Column("locationid")]
    public int? Locationid { get; set; }

    [Column("behaviourtype")]
    public int Behaviourtype { get; set; }

    [Column("sourceagent")]
    public int? Sourceagent { get; set; }

    [Column("difficultyreward")]
    public int? Difficultyreward { get; set; }

    [Column("difficultymultiplier")]
    public double? Difficultymultiplier { get; set; }

    [InverseProperty("MissionidonfailNavigation")]
    public virtual ICollection<Mission> InverseMissionidonfailNavigation { get; set; } = new List<Mission>();

    [InverseProperty("MissionidonsuccessNavigation")]
    public virtual ICollection<Mission> InverseMissionidonsuccessNavigation { get; set; } = new List<Mission>();

    [ForeignKey("Issuerid")]
    [InverseProperty("Missions")]
    public virtual Missionissuer Issuer { get; set; }

    [InverseProperty("Mission")]
    public virtual ICollection<Missionenterpoint> Missionenterpoints { get; set; } = new List<Missionenterpoint>();

    [ForeignKey("Missionidonfail")]
    [InverseProperty("InverseMissionidonfailNavigation")]
    public virtual Mission MissionidonfailNavigation { get; set; }

    [ForeignKey("Missionidonsuccess")]
    [InverseProperty("InverseMissionidonsuccessNavigation")]
    public virtual Mission MissionidonsuccessNavigation { get; set; }

    [InverseProperty("Mission")]
    public virtual ICollection<Missionrequiredextension> Missionrequiredextensions { get; set; } = new List<Missionrequiredextension>();

    [InverseProperty("MissionNavigation")]
    public virtual ICollection<Missionrequiredmission> MissionrequiredmissionMissionNavigations { get; set; } = new List<Missionrequiredmission>();

    [InverseProperty("RequiredmissionNavigation")]
    public virtual ICollection<Missionrequiredmission> MissionrequiredmissionRequiredmissionNavigations { get; set; } = new List<Missionrequiredmission>();

    [InverseProperty("Mission")]
    public virtual ICollection<Missionrequiredstanding> Missionrequiredstandings { get; set; } = new List<Missionrequiredstanding>();

    [InverseProperty("Mission")]
    public virtual ICollection<Missionreward> Missionrewards { get; set; } = new List<Missionreward>();

    [InverseProperty("Mission")]
    public virtual ICollection<Missionstandingchange> Missionstandingchanges { get; set; } = new List<Missionstandingchange>();

    [InverseProperty("Mission")]
    public virtual ICollection<Missionstartitem> Missionstartitems { get; set; } = new List<Missionstartitem>();

    [ForeignKey("Missiontype")]
    [InverseProperty("Missions")]
    public virtual Missiontype MissiontypeNavigation { get; set; }

    [ForeignKey("Sourceagent")]
    [InverseProperty("Missions")]
    public virtual Missionagent SourceagentNavigation { get; set; }
}