// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("modulepropertymodifiers")]
public partial class Modulepropertymodifier
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("categoryflags")]
    public long Categoryflags { get; set; }

    [Column("basefield")]
    public int Basefield { get; set; }

    [Column("modifierfield")]
    public int Modifierfield { get; set; }
}