// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("mtproductprices")]
[Index("Productkey", Name = "IX_productprices", IsUnique = true)]
public partial class Mtproductprice
{
    [Required]
    [Column("productkey")]
    [StringLength(50)]
    [Unicode(false)]
    public string Productkey { get; set; }

    [Column("price")]
    public int Price { get; set; }
}