// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("newscategories")]
public partial class Newscategory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("category")]
    [StringLength(2000)]
    public string Category { get; set; }

    [InverseProperty("TypeNavigation")]
    public virtual ICollection<News> News { get; set; } = new List<News>();
}