// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("news")]
public partial class News
{
    [Key]
    [Column("idx")]
    public int Idx { get; set; }

    [Required]
    [Column("title")]
    [StringLength(128)]
    public string Title { get; set; }

    [Required]
    [Column("body")]
    [StringLength(4000)]
    public string Body { get; set; }

    [Column("ntime", TypeName = "smalldatetime")]
    public DateTime Ntime { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("language")]
    public int Language { get; set; }

    [ForeignKey("Type")]
    [InverseProperty("News")]
    public virtual Newscategory TypeNavigation { get; set; }
}