// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("npcbossinfo")]
public partial class Npcbossinfo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("flockid")]
    public int Flockid { get; set; }

    [Column("respawnNoiseFactor")]
    public double? RespawnNoiseFactor { get; set; }

    [Column("lootSplitFlag")]
    public bool LootSplitFlag { get; set; }

    [Column("outpostEID")]
    public long? OutpostEid { get; set; }

    [Column("stabilityPts")]
    public int? StabilityPts { get; set; }

    [Column("overrideRelations")]
    public bool OverrideRelations { get; set; }

    [Column("customDeathMessage")]
    [StringLength(128)]
    [Unicode(false)]
    public string CustomDeathMessage { get; set; }

    [Column("customAggressMessage")]
    [StringLength(128)]
    [Unicode(false)]
    public string CustomAggressMessage { get; set; }

    [Column("riftConfigId")]
    public int? RiftConfigId { get; set; }

    [Column("isAnnounced")]
    public bool IsAnnounced { get; set; }

    [Column("isServerWideAnnouncement")]
    public bool? IsServerWideAnnouncement { get; set; }

    [Column("isNoRadioDelay")]
    public bool? IsNoRadioDelay { get; set; }
}