// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("npcescalactions")]
public partial class Npcescalaction
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("presenceId")]
    public int PresenceId { get; set; }

    [Column("flockId")]
    public int FlockId { get; set; }

    [Column("level")]
    public int Level { get; set; }

    [Column("chance")]
    public double Chance { get; set; }
}