// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("npckills")]
[Index("Definition", Name = "IX_npckills", IsUnique = true)]
public partial class Npckill
{
    [Column("definition")]
    public int Definition { get; set; }

    [Column("amount")]
    public int Amount { get; set; }
}