// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("npcpresence")]
[Index("Name", Name = "IX_npcpresence_name", IsUnique = true)]
public partial class Npcpresence
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(128)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("topx")]
    public int Topx { get; set; }

    [Column("topy")]
    public int Topy { get; set; }

    [Column("bottomx")]
    public int Bottomx { get; set; }

    [Column("bottomy")]
    public int Bottomy { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    /// <summary>
    /// azert nullozhato h ki lehessen kapcsolni
    /// </summary>
    [Column("spawnid")]
    public int? Spawnid { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [Column("roaming")]
    public bool Roaming { get; set; }

    [Column("roamingrespawnseconds")]
    public int Roamingrespawnseconds { get; set; }

    [Column("presencetype")]
    public int Presencetype { get; set; }

    [Column("maxrandomflock")]
    public int? Maxrandomflock { get; set; }

    [Column("randomcenterx")]
    public int? Randomcenterx { get; set; }

    [Column("randomcentery")]
    public int? Randomcentery { get; set; }

    [Column("randomradius")]
    public int? Randomradius { get; set; }

    [Column("dynamiclifetime")]
    public int? Dynamiclifetime { get; set; }

    [Column("isbodypull")]
    public bool Isbodypull { get; set; }

    [Column("isrespawnallowed")]
    public bool Isrespawnallowed { get; set; }

    [Column("safebodypull")]
    public bool Safebodypull { get; set; }

    [Column("izgroupid")]
    public int? Izgroupid { get; set; }

    [Column("growthseconds")]
    public int? Growthseconds { get; set; }

    [InverseProperty("Presence")]
    public virtual ICollection<Npcflock> Npcflocks { get; set; } = new List<Npcflock>();

    [ForeignKey("Spawnid")]
    [InverseProperty("Npcpresences")]
    public virtual Npcspawn Spawn { get; set; }
}