// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("npcspawn")]
[Index("Name", Name = "IX_npcspawn", IsUnique = true)]
public partial class Npcspawn
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [InverseProperty("Spawn")]
    public virtual ICollection<Npcpresence> Npcpresences { get; set; } = new List<Npcpresence>();
}