// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("nspools")]
public partial class Nspool
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Pool")]
    public virtual ICollection<Nspoolmember> Nspoolmembers { get; set; } = new List<Nspoolmember>();

    [InverseProperty("SourcepoolNavigation")]
    public virtual ICollection<Nspoolrelation> NspoolrelationSourcepoolNavigations { get; set; } = new List<Nspoolrelation>();

    [InverseProperty("TargetpoolNavigation")]
    public virtual ICollection<Nspoolrelation> NspoolrelationTargetpoolNavigations { get; set; } = new List<Nspoolrelation>();
}