// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("nspoolmembers")]
public partial class Nspoolmember
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("poolid")]
    public int Poolid { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Nspoolmembers")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Poolid")]
    [InverseProperty("Nspoolmembers")]
    public virtual Nspool Pool { get; set; }
}