// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("nstemplates")]
[Index("Definition", "Field", Name = "IX_DefField", IsUnique = true)]
public partial class Nstemplate
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("field")]
    public int Field { get; set; }

    [Column("worstvalue")]
    public double Worstvalue { get; set; }

    [Column("bestvalue")]
    public double Bestvalue { get; set; }

    [Column("note")]
    public string Note { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Nstemplates")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Field")]
    [InverseProperty("Nstemplates")]
    public virtual Aggregatefield FieldNavigation { get; set; }
}