// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("opp_reimburselog")]
public partial class OppReimburselog
{
    public int Id { get; set; }

    public int ReimburseTo { get; set; }

    public int ReimburseBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReimburseTime { get; set; }

    public int EntityId { get; set; }

    [Required]
    [StringLength(16)]
    public string ItemType { get; set; }

    public int Qty { get; set; }
}