// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("packages")]
public partial class Package
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(64)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("note")]
    public string Note { get; set; }

    [InverseProperty("Package")]
    public virtual ICollection<Accountpremiumpackage> Accountpremiumpackages { get; set; } = new List<Accountpremiumpackage>();

    [InverseProperty("Package")]
    public virtual ICollection<Packageitem> Packageitems { get; set; } = new List<Packageitem>();
}