// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("paymentproducts")]
[Index("Productname", Name = "IX_paymentproducts", IsUnique = true)]
[Index("Hash", Name = "IX_paymentproducts_hash", IsUnique = true)]
public partial class Paymentproduct
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("productname")]
    [StringLength(256)]
    [Unicode(false)]
    public string Productname { get; set; }

    [Column("priceUSD")]
    public double PriceUsd { get; set; }

    [Column("priceEUR")]
    public double PriceEur { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("available")]
    public bool Available { get; set; }

    [Column("hash")]
    public int Hash { get; set; }

    [Column("priceFormerEUR")]
    public double? PriceFormerEur { get; set; }

    [Column("priceFormerUSD")]
    public double? PriceFormerUsd { get; set; }

    [Column("timespan")]
    public int Timespan { get; set; }

    [Column("recurring")]
    public int? Recurring { get; set; }

    [Column("aws_Sku")]
    [StringLength(64)]
    [Unicode(false)]
    public string AwsSku { get; set; }

    [Column("visible")]
    public bool Visible { get; set; }

    [Column("trialonly")]
    public bool Trialonly { get; set; }

    [Column("ingame")]
    public bool Ingame { get; set; }

    [Column("displayorder")]
    public int Displayorder { get; set; }
}