// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("pbsconnections")]
[Index("Targeteid", Name = "IX_target")]
public partial class Pbsconnection
{
    [Column("id")]
    public int Id { get; set; }

    [Column("sourceeid")]
    public long Sourceeid { get; set; }

    [Column("targeteid")]
    public long Targeteid { get; set; }

    [Column("weight")]
    public double Weight { get; set; }
}