// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("pbslog")]
public partial class Pbslog
{
    [Column("corporationeid")]
    public long Corporationeid { get; set; }

    [Column("nodeeid")]
    public long Nodeeid { get; set; }

    [Column("nodedefinition")]
    public int Nodedefinition { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("eventtype")]
    public int Eventtype { get; set; }

    [Column("issuercharacterid")]
    public int? Issuercharacterid { get; set; }

    [Column("takeovercorporationeid")]
    public long? Takeovercorporationeid { get; set; }

    [Column("othernodeeid")]
    public long? Othernodeeid { get; set; }

    [Column("othernodedefinition")]
    public int? Othernodedefinition { get; set; }

    [Column("materialdefinition")]
    public int? Materialdefinition { get; set; }

    [Column("materialamount")]
    public int? Materialamount { get; set; }

    [Column("zoneid")]
    public int? Zoneid { get; set; }

    [Column("killercharacterid")]
    public int? Killercharacterid { get; set; }

    [Column("reinforcecounter")]
    public int? Reinforcecounter { get; set; }
}