// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("pbsregisteredmembers")]
public partial class Pbsregisteredmember
{
    [Column("eid")]
    public long Eid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }
}