// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("pbstrash")]
public partial class Pbstrash
{
    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("baseeid")]
    public long Baseeid { get; set; }

    [Column("waskilled")]
    public bool Waskilled { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }
}