// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("polls")]
public partial class Poll
{
    [Key]
    [Column("pollid")]
    public int Pollid { get; set; }

    [Required]
    [Column("topic")]
    public string Topic { get; set; }

    [Column("participation")]
    public int Participation { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Column("started", TypeName = "smalldatetime")]
    public DateTime Started { get; set; }

    [Column("ended", TypeName = "smalldatetime")]
    public DateTime? Ended { get; set; }
}