// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("pollchoices")]
public partial class Pollchoice
{
    [Column("pollid")]
    public int Pollid { get; set; }

    [Column("choiceid")]
    public int Choiceid { get; set; }

    [Required]
    [Column("choicetext")]
    public string Choicetext { get; set; }

    [ForeignKey("Pollid")]
    public virtual Poll Poll { get; set; }
}