// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("pollanswers")]
public partial class Pollanswer
{
    [Column("pollid")]
    public int Pollid { get; set; }

    [Column("accountid")]
    public int Accountid { get; set; }

    [Column("answerid")]
    public int Answerid { get; set; }

    [ForeignKey("Pollid")]
    public virtual Poll Poll { get; set; }
}