// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("premadechatmessage")]
[Index("Name", Name = "UQ__premadec__72E12F1B7D72412D", IsUnique = true)]
public partial class Premadechatmessage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(32)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("message")]
    [StringLength(2000)]
    public string Message { get; set; }
}