// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("premademail")]
[Index("Name", Name = "UQ__premadem__72E12F1B8CF5B2D4", IsUnique = true)]
public partial class Premademail
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(32)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("subject")]
    [StringLength(128)]
    public string Subject { get; set; }

    [Required]
    [Column("body")]
    [StringLength(2000)]
    public string Body { get; set; }
}