// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("productionlog")]
[Index("Usecorporationwallet", "Characterid", "Productiontime", Name = "IX_prodlog")]
public partial class Productionlog
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("amount")]
    public int Amount { get; set; }

    [Column("productiontime", TypeName = "datetime")]
    public DateTime Productiontime { get; set; }

    [Column("productiontype")]
    public int Productiontype { get; set; }

    [Column("durationsecs")]
    public int Durationsecs { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [Column("usecorporationwallet")]
    public bool Usecorporationwallet { get; set; }
}