// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("productionlines")]
public partial class Productionline
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("facilityeid")]
    public long Facilityeid { get; set; }

    [Column("runningproductionid")]
    public int? Runningproductionid { get; set; }

    [Column("targetdefinition")]
    public int Targetdefinition { get; set; }

    [Column("materialefficiency")]
    public double Materialefficiency { get; set; }

    [Column("timeefficiency")]
    public double Timeefficiency { get; set; }

    [Column("cycles")]
    public int Cycles { get; set; }

    [Column("rounds")]
    public int Rounds { get; set; }

    [Column("cprgeid")]
    public long? Cprgeid { get; set; }
}