// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("riftdestinations")]
public partial class Riftdestination
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("groupId")]
    public int GroupId { get; set; }

    [Column("zoneId")]
    public int ZoneId { get; set; }

    [Column("x")]
    public int? X { get; set; }

    [Column("y")]
    public int? Y { get; set; }

    [Column("weight")]
    public int Weight { get; set; }
}