// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("robotsavedeffects")]
public partial class Robotsavedeffect
{
    [Column("id")]
    public int Id { get; set; }

    [Column("owner")]
    public long Owner { get; set; }

    [Column("effects", TypeName = "text")]
    public string Effects { get; set; }
}