// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("serverinfo")]
public partial class Serverinfo
{
    [Column("name")]
    [StringLength(512)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(2048)]
    public string Description { get; set; }

    [Column("contact")]
    [StringLength(512)]
    public string Contact { get; set; }

    [Column("isopen")]
    public bool Isopen { get; set; }

    [Column("isbroadcast")]
    public bool Isbroadcast { get; set; }
}