// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("settings")]
public partial class Setting
{
    [Key]
    [Column("varkey")]
    [StringLength(64)]
    [Unicode(false)]
    public string Varkey { get; set; }

    [Required]
    [Column("varvalue")]
    [StringLength(512)]
    [Unicode(false)]
    public string Varvalue { get; set; }

    [Column("notes")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Notes { get; set; }
}