// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("sparkextensions")]
public partial class Sparkextension
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("sparkid")]
    public int Sparkid { get; set; }

    [Column("extensionid")]
    public int Extensionid { get; set; }

    [Column("extensionlevel")]
    public int Extensionlevel { get; set; }

    [ForeignKey("Extensionid")]
    [InverseProperty("Sparkextensions")]
    public virtual Extension Extension { get; set; }

    [ForeignKey("Sparkid")]
    [InverseProperty("Sparkextensions")]
    public virtual Spark Spark { get; set; }
}