// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("standings")]
[Index("Source", "Target", Name = "IX_standings", IsUnique = true)]
public partial class Standing
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("source")]
    public long Source { get; set; }

    [Column("target")]
    public long Target { get; set; }

    [Column("standing")]
    public double Standing1 { get; set; }
}