// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("techtreelog")]
public partial class Techtreelog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("logType")]
    public int LogType { get; set; }

    [Column("character")]
    public int Character { get; set; }

    [Column("corporationEid")]
    public long? CorporationEid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("pointType")]
    public int PointType { get; set; }

    [Column("amount")]
    public int Amount { get; set; }

    [Column("created", TypeName = "datetime")]
    public DateTime Created { get; set; }
}