// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("techtree")]
[Index("Parentdefinition", "Childdefinition", Name = "IX_parentchild", IsUnique = true)]
public partial class Techtree
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("parentdefinition")]
    public int Parentdefinition { get; set; }

    [Column("childdefinition")]
    public int Childdefinition { get; set; }

    [Column("groupID")]
    public int GroupId { get; set; }

    [Column("x")]
    public int X { get; set; }

    [Column("y")]
    public int Y { get; set; }

    [Column("enablerextensionid")]
    public int? Enablerextensionid { get; set; }
}