// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("techlinemember")]
public partial class Techlinemember
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("techlineid")]
    public int Techlineid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("position")]
    public int Position { get; set; }

    [Column("points")]
    public double Points { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Techlinemembers")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Techlineid")]
    [InverseProperty("Techlinemembers")]
    public virtual Techline Techline { get; set; }
}