// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("teleportdescriptions")]
[Index("Description", Name = "IX_teleportdescriptions", IsUnique = true)]
public partial class Teleportdescription
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("description")]
    [StringLength(128)]
    [Unicode(false)]
    public string Description { get; set; }

    /// <summary>
    /// teleport from map using the column
    /// </summary>
    [Column("sourcecolumn")]
    public long? Sourcecolumn { get; set; }

    /// <summary>
    /// teleport around the column
    /// </summary>
    [Column("targetcolumn")]
    public long? Targetcolumn { get; set; }

    [Column("sourcezone")]
    public int? Sourcezone { get; set; }

    /// <summary>
    /// the range the column picks the robot up.   this field is not set if the sourcebase is used 
    /// </summary>
    [Column("sourcerange")]
    public int? Sourcerange { get; set; }

    [Column("targetzone")]
    public int? Targetzone { get; set; }

    [Column("targetx")]
    public double? Targetx { get; set; }

    [Column("targety")]
    public double? Targety { get; set; }

    [Column("targetz")]
    public double? Targetz { get; set; }

    [Column("targetrange")]
    public int? Targetrange { get; set; }

    /// <summary>
    /// in seconds
    /// </summary>
    [Column("usetimeout")]
    public int Usetimeout { get; set; }

    [Column("listable")]
    public bool Listable { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [Column("sourcecolumnname")]
    [StringLength(128)]
    public string Sourcecolumnname { get; set; }

    [Column("targetcolumnname")]
    [StringLength(128)]
    public string Targetcolumnname { get; set; }

    [InverseProperty("Teleportchannel")]
    public virtual ICollection<Missionenterpoint> Missionenterpoints { get; set; } = new List<Missionenterpoint>();

    [ForeignKey("Sourcezone")]
    [InverseProperty("TeleportdescriptionSourcezoneNavigations")]
    public virtual Zone SourcezoneNavigation { get; set; }

    [ForeignKey("Targetzone")]
    [InverseProperty("TeleportdescriptionTargetzoneNavigations")]
    public virtual Zone TargetzoneNavigation { get; set; }
}