// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("terraformprojectregistration")]
[Index("Projectid", "Characterid", Name = "IX_terraformprojectregistration_1", IsUnique = true)]
public partial class Terraformprojectregistration
{
    [Column("id")]
    public int Id { get; set; }

    [Column("projectid")]
    public int Projectid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("role")]
    public int Role { get; set; }
}