// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("terraformprojects")]
[Index("Ownercharacterid", Name = "IX_terraformprojects")]
public partial class Terraformproject
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("title")]
    [StringLength(512)]
    public string Title { get; set; }

    [Column("ownercharacterid")]
    public int Ownercharacterid { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("topx")]
    public int Topx { get; set; }

    [Column("topy")]
    public int Topy { get; set; }

    [Column("bottomx")]
    public int Bottomx { get; set; }

    [Column("bottomy")]
    public int Bottomy { get; set; }

    [Column("version")]
    public int Version { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("lastmodified", TypeName = "datetime")]
    public DateTime Lastmodified { get; set; }

    [Column("validuntil", TypeName = "datetime")]
    public DateTime Validuntil { get; set; }

    [Column("data")]
    public byte[] Data { get; set; }
}