// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("traceips")]
public partial class Traceip
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("ip")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ip { get; set; }

    [Column("name")]
    [StringLength(1024)]
    [Unicode(false)]
    public string Name { get; set; }
}