// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("traceroutelog")]
public partial class Traceroutelog
{
    [Column("accountid")]
    public int Accountid { get; set; }

    [Required]
    [Column("sessionguid")]
    [StringLength(64)]
    [Unicode(false)]
    public string Sessionguid { get; set; }

    [Column("ip")]
    [StringLength(32)]
    [Unicode(false)]
    public string Ip { get; set; }

    [Column("step")]
    public int Step { get; set; }

    [Column("ipstatus")]
    public int Ipstatus { get; set; }

    [Column("roundtriptime")]
    public long Roundtriptime { get; set; }

    [Column("tracetime", TypeName = "datetime")]
    public DateTime Tracetime { get; set; }

    [Column("fromclient")]
    public bool Fromclient { get; set; }

    [Column("country")]
    [StringLength(128)]
    [Unicode(false)]
    public string Country { get; set; }

    [Column("tracedipid")]
    public int Tracedipid { get; set; }
}