// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("transportassignments")]
public partial class Transportassignment
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("creation", TypeName = "datetime")]
    public DateTime Creation { get; set; }

    [Column("sourcebaseeid")]
    public long Sourcebaseeid { get; set; }

    [Column("targetbaseeid")]
    public long Targetbaseeid { get; set; }

    [Column("ownercharacterid")]
    public int Ownercharacterid { get; set; }

    [Column("reward")]
    public long Reward { get; set; }

    [Column("collateral")]
    public long Collateral { get; set; }

    [Column("taken")]
    public bool Taken { get; set; }

    [Column("volunteercharacterid")]
    public int? Volunteercharacterid { get; set; }

    [Column("containereid")]
    public long Containereid { get; set; }

    [Required]
    [Column("containername")]
    [StringLength(10)]
    [Unicode(false)]
    public string Containername { get; set; }

    [Column("volume")]
    public double Volume { get; set; }

    [Column("expiry", TypeName = "datetime")]
    public DateTime Expiry { get; set; }

    [Column("started", TypeName = "datetime")]
    public DateTime? Started { get; set; }

    [Column("retrieved")]
    public bool Retrieved { get; set; }
}