// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("transportassignmenttimes")]
public partial class Transportassignmenttime
{
    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("eventtime", TypeName = "datetime")]
    public DateTime Eventtime { get; set; }

    [Column("sourcebase")]
    public long Sourcebase { get; set; }

    [Column("targetbase")]
    public long Targetbase { get; set; }

    [Column("distance")]
    public double Distance { get; set; }

    [Column("volume")]
    public double Volume { get; set; }

    [Column("totalseconds")]
    public double Totalseconds { get; set; }

    [Column("multiplier")]
    public double Multiplier { get; set; }
}