// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("vendors")]
public partial class Vendor
{
    [Column("vendorEID")]
    public long VendorEid { get; set; }

    [Column("marketEID")]
    public long? MarketEid { get; set; }

    [Column("vendorsellprofit")]
    public double Vendorsellprofit { get; set; }

    [Column("vendorbuyprofit")]
    public double Vendorbuyprofit { get; set; }

    [Column("note")]
    [StringLength(2048)]
    public string Note { get; set; }
}