// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("vendorpresetvalues")]
[Index("Presetid", "Definition", "Issell", Name = "IX_vendorpresetvalues", IsUnique = true)]
public partial class Vendorpresetvalue
{
    [Key]
    [Column("idx")]
    public int Idx { get; set; }

    [Column("presetid")]
    public int Presetid { get; set; }

    [Column("definition")]
    public int Definition { get; set; }

    [Column("issell")]
    public bool Issell { get; set; }

    [Column("price")]
    public double Price { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("duration")]
    public int Duration { get; set; }

    [ForeignKey("Definition")]
    [InverseProperty("Vendorpresetvalues")]
    public virtual Entitydefault DefinitionNavigation { get; set; }

    [ForeignKey("Presetid")]
    [InverseProperty("Vendorpresetvalues")]
    public virtual Vendorpreset Preset { get; set; }
}