// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Keyless]
[Table("voteentries")]
public partial class Voteentry
{
    [Column("voteid")]
    public int Voteid { get; set; }

    [Column("characterid")]
    public int Characterid { get; set; }

    [Column("voteentry")]
    public bool Voteentry1 { get; set; }

    [Column("entrydate", TypeName = "smalldatetime")]
    public DateTime Entrydate { get; set; }

    [ForeignKey("Voteid")]
    public virtual Vote Vote { get; set; }
}