// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("zoneriftsconfig")]
[Index("Zoneid", Name = "UQ__zonerift__2F74DB501000E971", IsUnique = true)]
public partial class Zoneriftsconfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("maxrifts")]
    public int Maxrifts { get; set; }

    [Column("maxlevel")]
    public int Maxlevel { get; set; }
}