// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("zoneuserentities")]
public partial class Zoneuserentity
{
    [Key]
    [Column("eid")]
    public long Eid { get; set; }

    [Column("zoneid")]
    public int Zoneid { get; set; }

    [Column("x")]
    public double X { get; set; }

    [Column("y")]
    public double Y { get; set; }

    [Column("z")]
    public double Z { get; set; }

    [Column("orientation")]
    public byte Orientation { get; set; }
}