// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Perpetuum.DataContext.Models;

[Table("zoneentities")]
[Index("Eid", Name = "IX_zoneentities_eid_uk", IsUnique = true)]
[Index("Synckey", Name = "IX_zoneentities_sync")]
public partial class Zoneentity
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("zoneID")]
    public int ZoneId { get; set; }

    [Column("eid")]
    public long? Eid { get; set; }

    [Column("definition")]
    public int? Definition { get; set; }

    [Column("owner")]
    public long? Owner { get; set; }

    [Column("ename")]
    [StringLength(128)]
    [Unicode(false)]
    public string Ename { get; set; }

    [Column("x")]
    public double X { get; set; }

    [Column("y")]
    public double Y { get; set; }

    [Column("z")]
    public double Z { get; set; }

    [Column("orientation")]
    public byte Orientation { get; set; }

    [Column("enabled")]
    public bool Enabled { get; set; }

    [Column("note")]
    [StringLength(2000)]
    public string Note { get; set; }

    [Column("runtime")]
    public bool Runtime { get; set; }

    [Column("synckey")]
    [StringLength(50)]
    [Unicode(false)]
    public string Synckey { get; set; }

    [ForeignKey("ZoneId")]
    [InverseProperty("Zoneentities")]
    public virtual Zone Zone { get; set; }
}